### PR TITLE
return exception when unavailable segments on empty broker response

### LINKED ISSUE #7811: /query/sql silently returns when all servers are down
Problem Statement:
Need a reliable way to tell if query result is valid to use when all servers are down.

Repro steps:
1. Take down all servers (I did "svc -d /etc/service/pinot-server")
2. Execute a query via broker ("select * from MyTable limit 10" via /query/sql)

Expected Results:
HTTP response has a non-200 status code, or "exceptions" field in response content shows error message about no server available.

Actual Results:
HTTP response status code = 200
Response:
{"exceptions":[],"numServersQueried":0,"numServersResponded":0,"numSegmentsQueried":0,"numSegmentsProcessed":0,"numSegmentsMatched":0,"numConsumingSegmentsQueried":0,"numDocsScanned":0,"numEntriesScannedInFilter":0,"numEntriesScannedPostFilter":0,"numGroupsLimitReached":false,"totalDocs":0,"timeUsedMs":0,"offlineThreadCpuTimeNs":0,"realtimeThreadCpuTimeNs":0,"segmentStatistics":[],"traceInfo":{},"numRowsResultSet":0,"minConsumingFreshnessTimeMs":0}

Questions:
I see in this case, "resultTable" is not present and "numServersQueried" is 0. Are those the recommended way to tell is query result is valid? Or do we think some more explicit way (status code ideally?) should be implemented?

### PR DESCRIPTION
**Pull request by jadami10**
## Description

This fixes #7811. In #7264 we added exceptions when not all segments are available, but this was one case that was missed. Specifically if all servers are unavailable, both realtime and offline requests become null, but there are still unavailable segments. This adds the exception to the broker response.

There's no unit tests here which makes it quite difficult for me to setup something. But I tested locally by running  the realtime quickstart
- i ran the query and saw results
- i "dropped" the server and saw no results
- i then applied this fix, reran the server drop, and saw the exception
image

## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)
## Documentation

This will get encompassed whenever the new error code documentation is done.

### CODE REVIEW

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java [hunk 1]
```diff
@@ -459,7 +459,13 @@ private BrokerResponseNative handleSQLRequest(long requestId, String query, Json
     if (offlineBrokerRequest == null && realtimeBrokerRequest == null) {
       LOGGER.info("No server found for request {}: {}", requestId, query);
       _brokerMetrics.addMeteredTableValue(rawTableName, BrokerMeter.NO_SERVER_FOUND_EXCEPTIONS, 1);
-      return BrokerResponseNative.EMPTY_RESULT;
+      BrokerResponseNative brokerResponse = BrokerResponseNative.EMPTY_RESULT;
+      if (numUnavailableSegments > 0) {
```
Comment (siddharthteotia) [inline pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:463]: I think the intention of the PR https://github.com/apache/pinot/pull/7397 was to always add this exception to BrokerResponse if numUnavailableSegments is > 0 and this case was missed ? 

So may be we just do this once by moving the code at line 512 to proper place that covers all scenarios unconditionally ?

Comment (jadami10) [reply pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java]: It's a little tough to do with the way the code is structured. We can't return early when there's segments missing because many use cases still want partial results if possible. And there are several places in this function that short-circuit and return their own response before adding previous exceptions.

But I've moved the code up to create a list of exceptions we can add to. And I've added the missing segments exception to the timeout response as well.

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java [hunk 2]
```diff
@@ -456,10 +456,18 @@ private BrokerResponseNative handleSQLRequest(long requestId, String query, Json
     int numUnavailableSegments = unavailableSegments.size();
     requestStatistics.setNumUnavailableSegments(numUnavailableSegments);
 
+    List<QueryProcessingException> exceptions = new ArrayList<>();
+    if (numUnavailableSegments > 0) {
+      exceptions.add(new QueryProcessingException(QueryException.BROKER_SEGMENT_UNAVAILABLE_ERROR_CODE,
+          String.format("%d segments %s unavailable", numUnavailableSegments, unavailableSegments)));
+    }
```
Comment (Jackie-Jiang) [inline pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:463]: Here we can store a list of `ProcessingException` which is easier to manage
```suggestion
    List<ProcessingException> exceptions = new ArrayList<>();
    if (numUnavailableSegments > 0) {
      exceptions.add(QueryException.getException(QueryException.BROKER_SEGMENT_UNAVAILABLE_ERROR_CODE,
          String.format("%d segments %s unavailable", numUnavailableSegments, unavailableSegments)));
    }
```

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java [hunk 3]
```diff
@@ -456,10 +456,18 @@ private BrokerResponseNative handleSQLRequest(long requestId, String query, Json
...
+
     if (offlineBrokerRequest == null && realtimeBrokerRequest == null) {
       LOGGER.info("No server found for request {}: {}", requestId, query);
       _brokerMetrics.addMeteredTableValue(rawTableName, BrokerMeter.NO_SERVER_FOUND_EXCEPTIONS, 1);
-      return BrokerResponseNative.EMPTY_RESULT;
+      BrokerResponseNative brokerResponse = BrokerResponseNative.EMPTY_RESULT;
+      brokerResponse.addToExceptions(exceptions);
+      return brokerResponse;
```
Comment (Jackie-Jiang) [inline pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:470]: (major) We cannot modify the constant broker response. Here we need to create a new one. If we apply the suggested change above, we can directly use the exception constructor
```suggestion
      return new BrokerResponseNative(exceptions);
```

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java [hunk 4]
```diff
@@ -486,14 +494,18 @@ private BrokerResponseNative handleSQLRequest(long requestId, String query, Json
       String errorMessage = e.getMessage();
       LOGGER.info("{} {}: {}", errorMessage, requestId, query);
       _brokerMetrics.addMeteredTableValue(rawTableName, BrokerMeter.REQUEST_TIMEOUT_BEFORE_SCATTERED_EXCEPTIONS, 1);
-      return new BrokerResponseNative(QueryException.getException(QueryException.BROKER_TIMEOUT_ERROR, errorMessage));
+      BrokerResponseNative brokerResponse =
+          new BrokerResponseNative(QueryException.getException(QueryException.BROKER_TIMEOUT_ERROR, errorMessage));
+      brokerResponse.addToExceptions(exceptions);
+      return brokerResponse;
```
Comment (Jackie-Jiang) [inline pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java:500]: This can also be simplified:
```suggestion
      exceptions.add(QueryException.getException(QueryException.BROKER_TIMEOUT_ERROR, errorMessage));
      return new BrokerResponseNative(exceptions);
```

**Review by Jackie-Jiang — COMMENTED** [review]
Good catch!

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java (hunk 2 above)
Comment (jadami10) [reply pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java]: The only downside of this is under the hood, `getException` does
```
String errorType = processingException.getMessage();
    ProcessingException copiedProcessingException = processingException.deepCopy();
    copiedProcessingException.setMessage(errorType + ":\n" + errorMessage);
    return copiedProcessingException;
```
which is setting the error message to `"message": "null:\n1 segments [meetupRsvp_REALTIME_1637786040816_0__0__1637786041067] unavailable"`. The `null:\n` looks weird. I could make that code not do that on nulls, but I have no idea what else changes at that point.

File: pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java (hunk 3 above)
Comment (jadami10) [reply pinot-broker/src/main/java/org/apache/pinot/broker/requesthandler/BaseBrokerRequestHandler.java]: oof, good catch.

**Review by Jackie-Jiang — APPROVED** [review]
LGTM
