### PR TITLE
Cache Deleted Segment Names in Server to Avoid SegmentMissingError

### LINKED ISSUE #9371: Segments Deleted Due to Retention Can Cause Query Failures with ServerSegmentMissing Error
We recently enabled the feature to return exceptions for cases when some segments are missing (as opposed to returning partial results).

This feature was rolled out in #7823.

After enabling it we have started seeing the following error occasionally for our Realtime tables. On digging a bit we found that this error comes when a segment is deleted due to retention.

```
ServerSegmentMissing:1 segments [<segment-name>] missing on server: <server-name>, errorCode:235
```

### PR DESCRIPTION
**Pull request by ankitsultana**
Added a UT. fixes #9371

cc: @chenboat @yupeng9 @Jackie-Jiang

### CODE REVIEW

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/BaseTableDataManager.java [hunk 1]
```diff
@@ -411,6 +429,31 @@ public void addOrReplaceSegment(String segmentName, IndexLoadingConfig indexLoad
...
   }
 
+  /**
+   * _segmentDataManagerMap is used for fetching segments that need to be queried. If a new segment is created,
+   * calling this method ensures that all queries in the future can use the new segment. This method may replace an
+   * existing segment with the same name.
+   */
+  @Nullable
+  protected SegmentDataManager registerSegment(String segmentName, SegmentDataManager segmentDataManager) {
+    SegmentDataManager oldSegmentDataManager = _segmentDataManagerMap.put(segmentName, segmentDataManager);
```
Comment (ankitsultana) [inline pinot-core/src/main/java/org/apache/pinot/core/data/manager/BaseTableDataManager.java:439]: I think we may wanna make `_segmentDataManagerMap` private so concrete classes that extend `BaseTableDataManager` use the map only via the provided methods here.

File: pinot-core/src/main/java/org/apache/pinot/core/query/executor/ServerQueryExecutorV1Impl.java [hunk 2]
```diff
@@ -191,8 +192,13 @@ private DataTable processQueryInternal(ServerQueryRequest queryRequest, Executor
...
 
     List<String> segmentsToQuery = queryRequest.getSegmentsToQuery();
-    List<String> missingSegments = new ArrayList<>();
-    List<SegmentDataManager> segmentDataManagers = tableDataManager.acquireSegments(segmentsToQuery, missingSegments);
+    List<String> unAcquiredSegments = new ArrayList<>();
+    List<SegmentDataManager> segmentDataManagers = tableDataManager.acquireSegments(
+        segmentsToQuery, unAcquiredSegments);
+    List<String> missingSegments =
+        unAcquiredSegments.stream()
+            .filter(segmentName -> !tableDataManager.isSegmentDeletedRecently(segmentName))
```
Comment (jackjlli) [inline pinot-core/src/main/java/org/apache/pinot/core/query/executor/ServerQueryExecutorV1Impl.java:200]: Suggest moving this logic inside the if block of Line 301 so that pinot-server doesn't have to do it for all the queries all the time.

File: pinot-server/src/main/java/org/apache/pinot/server/starter/helix/HelixInstanceDataManagerConfig.java [hunk 3]
```diff
@@ -121,8 +121,13 @@ public class HelixInstanceDataManagerConfig implements InstanceDataManagerConfig
   // Size of cache that holds errors.
   private static final String ERROR_CACHE_SIZE = "error.cache.size";
 
+  private static final String DELETED_SEGMENTS_CACHE_SIZE = "table.deleted.segments.cache.size";
+  private static final String DELETED_SEGMENTS_CACHE_TTL_MINUTES = "table.deleted.segments.cache.ttl.minutes";
+
   private final static String[] REQUIRED_KEYS = {INSTANCE_ID, INSTANCE_DATA_DIR, READ_MODE};
   private static final long DEFAULT_ERROR_CACHE_SIZE = 100L;
+  private static final int DEFAULT_DELETED_SEGMENTS_CACHE_SIZE = 10_000;
+  private static final int DEFAULT_DELETED_SEGMENTS_CACHE_TTL_MINUTES = 10;
```
Comment (jackjlli) [inline pinot-server/src/main/java/org/apache/pinot/server/starter/helix/HelixInstanceDataManagerConfig.java:130]: Usually the state transition doesn't take too much time (at most sub-seconds) on spreading the helix messages and notifications. If it really needs 10 minutes to converge, it probably means there is something wrong in your cluster and needs to be fixed.

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/BaseTableDataManager.java [hunk 4]
```diff
@@ -411,6 +429,31 @@ public void addOrReplaceSegment(String segmentName, IndexLoadingConfig indexLoad
...
+
+  /**
+   * De-registering a segment ensures that no query uses the given segment until a segment with that name is
+   * re-registered. There may be scenarios where the broker thinks that a segment is available even though it has
+   * been de-registered in the servers (either due to manual deletion or retention). In such cases, acquireSegments
+   * will mark those segments as missingSegments. The caller can use {@link #isSegmentDeletedRecently(String)} to
+   * identify this scenario.
+   */
+  @Nullable
+  protected SegmentDataManager deRegisterSegment(String segmentName) {
```
Comment (jackjlli) [inline pinot-core/src/main/java/org/apache/pinot/core/data/manager/BaseTableDataManager.java:452]: nit: unregisterSegment

**Review by jackjlli — COMMENTED** [review]
I feel it's a legitimate behavior that server finished segment deletion before controller updates the EV, as controller won't update it until it receives the message from servers saying the state transition is completed, not to mention brokers listen to the notification of EV changes to update routing table, which is the very last step.

General speaking I think the better way (or best practice) is to avoid querying the very last pieces of segments, by adding the time column in your filter clauses of the queries. If the Pinot table you are querying is a hybrid table, the oldest realtime segments won't be queried because of the correct time boundary maintained internally. Thus we won't see such exception even if we enable the exception returned feature that you implemented. Similarly, if we only query the realtime only or offline only table, we shouldn't query the oldest segments, as the behavior of them is harder to predict in a distributed world. Adding such cache will definitely work while it seems more like a hack to get around with it.

**Comment by ankitsultana** [comment]
> General speaking I think the better way (or best practice) is to avoid querying the very last pieces of segments, by adding the time column in your filter clauses of the queries.

This is discussed in #9371. It doesn't handle the scenario where a segment is manually deleted. Requiring users to add filters in the query isn't tenable, and the alternative is to automatically prune such segments in the Broker. But that's not doable right now since Broker doesn't watch TableConfig changes (retention may be changed by users).

**Comment by jackjlli** [comment]
>  It doesn't handle the scenario where a segment is manually deleted.

I don't think it's a good idea to manually delete segments when segments are being queried. The better way is to disable them before doing the deletion.

> Requiring users to add filters in the query isn't tenable. 

I'm not saying we should ask users to do that but your client system to append the predicate in the filter clause.

> and the alternative is to automatically prune such segments in the Broker. But that's not doable right now since Broker doesn't watch TableConfig changes (retention may be changed by users).

I'm not sure I fully understand your statement here. Pruning segments has nothing to do with table config changes. And in fact table config is already cached in broker, and there is a watcher in TableCache to listen the table config changes in ZK.

**Comment by ankitsultana** [comment]
> I'm not sure I fully understand your statement here. Pruning segments has nothing to do with table config changes. And in fact table config is already cached in broker, and there is a watcher in TableCache to listen the table config changes in ZK.

For instance when a user changes the retention, it may take a while for the changes to be reflected in Broker segment pruners. @Jackie-Jiang: I think you mentioned that this scenario may cause an issue since Broker doesn't listen to table-config changes. Can you share those concerns here?

File: pinot-core/src/main/java/org/apache/pinot/core/query/executor/ServerQueryExecutorV1Impl.java [hunk 5]
```diff
@@ -191,8 +192,9 @@ private DataTable processQueryInternal(ServerQueryRequest queryRequest, Executor
     }
 
     List<String> segmentsToQuery = queryRequest.getSegmentsToQuery();
-    List<String> missingSegments = new ArrayList<>();
-    List<SegmentDataManager> segmentDataManagers = tableDataManager.acquireSegments(segmentsToQuery, missingSegments);
+    List<String> unAcquiredSegments = new ArrayList<>();
```
Comment (chenboat) [inline pinot-core/src/main/java/org/apache/pinot/core/query/executor/ServerQueryExecutorV1Impl.java:195]: notAcquiredSegments instead of unAcquiredSegments.

**Review by chenboat — APPROVED** [review]

File: pinot-core/src/main/java/org/apache/pinot/core/query/executor/ServerQueryExecutorV1Impl.java [hunk 6]
```diff
@@ -291,12 +293,18 @@ private DataTable processQueryInternal(ServerQueryRequest queryRequest, Executor
     //
     // After step 2 but before step 4, segment will be missing on server side
     // TODO: Change broker to watch both IdealState and ExternalView to not query the removed segments
-    int numMissingSegments = missingSegments.size();
-    if (numMissingSegments != 0) {
-      dataTable.addException(QueryException.getException(QueryException.SERVER_SEGMENT_MISSING_ERROR,
-          String.format("%d segments %s missing on server: %s", numMissingSegments, missingSegments,
-              _instanceDataManager.getInstanceId())));
-      _serverMetrics.addMeteredTableValue(tableNameWithType, ServerMeter.NUM_MISSING_SEGMENTS, numMissingSegments);
+    if (unAcquiredSegments.size() > 0) {
```
Comment (chenboat) [inline pinot-core/src/main/java/org/apache/pinot/core/query/executor/ServerQueryExecutorV1Impl.java:296]: Add unit tests.

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/BaseTableDataManager.java [hunk 7]
```diff
@@ -100,6 +103,7 @@ public abstract class BaseTableDataManager implements TableDataManager {
   // Fixed size LRU cache with TableName - SegmentName pair as key, and segment related
   // errors as the value.
   protected LoadingCache<Pair<String, String>, SegmentErrorInfo> _errorCache;
+  protected Cache<String, String> _deletedSegments;
```
[the remark this answers is not in the document]
Comment (jackjlli) [reply pinot-core/src/main/java/org/apache/pinot/core/data/manager/BaseTableDataManager.java:106]: nit: rename it to sth like `_recentlyDeletedSegments`?

File: pinot-spi/src/main/java/org/apache/pinot/spi/config/instance/InstanceDataManagerConfig.java [hunk 8]
```diff
@@ -62,4 +62,8 @@ public interface InstanceDataManagerConfig {
   boolean isStreamSegmentDownloadUntar();
 
   long getStreamSegmentDownloadUntarRateLimit();
+
+  int getDeletedSegmentsCacheSize();
```
Comment (jackjlli) [inline pinot-spi/src/main/java/org/apache/pinot/spi/config/instance/InstanceDataManagerConfig.java:66]: nit: `getRecentlyDeletedSegmentsCacheSize()`

File: pinot-spi/src/main/java/org/apache/pinot/spi/config/instance/InstanceDataManagerConfig.java [hunk 9]
```diff
@@ -62,4 +62,8 @@ public interface InstanceDataManagerConfig {
...
+
+  int getDeletedSegmentsCacheTtlMinutes();
```
Comment (jackjlli) [inline pinot-spi/src/main/java/org/apache/pinot/spi/config/instance/InstanceDataManagerConfig.java:68]: Same here.

**Review by jackjlli — APPROVED** [review]
Minor but LGTM. Thanks for addressing it!

**Review by chenboat — APPROVED** [review]
