### PR TITLE
[Flaky-test] Fix LLCRealtimeClusterIntegrationTest.testForceCommitInBatches()

### LINKED ISSUE #15058: [Flaky-test] LLCRealtimeClusterIntegrationTest.testForceCommitInBatches
```
Error:  Failures: 
Error:    LLCRealtimeClusterIntegrationTest.testForceCommitInBatches:439->testForceCommitInternal:448 Failed to meet condition in 240000ms, error message: Error verifying force commit operation on table!
```

Failure run: https://github.com/apache/pinot/actions/runs/13315498779/job/37188350261?pr=15055

### PR DESCRIPTION
**Pull request by noob-se7en**
Fix #15058 

Test fails some of the times, ex: [https://github.com/apache/pinot/actions/runs/13082900152/job/36509811133](https://github.com/apache/pinot/actions/runs/13082900152/job/36509811133)

### CODE REVIEW

**Review by Jackie-Jiang — COMMENTED** [review]
We still want to test the case with batch size 1. Can you analyze the test failure log and see why the test is failing? Does increasing time out help here?

**Comment by noob-se7en** [comment]
> We still want to test the case with batch size 1. Can you analyze the test failure log and see why the test is failing? Does increasing time out help here?

Yes, But it's already close to 4 minutes. Don't want to further increase. 
Will analyse.

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotRealtimeTableResource.java [hunk 1]
```diff
@@ -256,15 +256,14 @@ public JsonNode getForceCommitJobStatus(
         _pinotLLCRealtimeSegmentManager.getSegmentsYetToBeCommitted(tableNameWithType, segmentsToCheck);
 
     if (segmentsYetToBeCommitted.size() < segmentsToCheck.size()) {
-      controllerJobZKMetadata.put(CommonConstants.ControllerJob.CONSUMING_SEGMENTS_YET_TO_BE_COMMITTED_LIST,
```
Comment (noob-se7en) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotRealtimeTableResource.java:259]: Why this?

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotRealtimeTableResource.java [hunk 2]
```diff
@@ -256,15 +256,14 @@ public JsonNode getForceCommitJobStatus(
...
-          JsonUtils.objectToString(segmentsYetToBeCommitted));
```
Comment (noob-se7en) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotRealtimeTableResource.java:260]: Why are we removing this?

Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotRealtimeTableResource.java:260]: Good catch, it is a bug

**Review by Jackie-Jiang — APPROVED** [review]
