### PR TITLE
Fix the potential deadlock for partial-upsert segment loading check

### LINKED ISSUE #10185: Restarting a Server with Partial Upsert Tables Leads to Tables in Bad State
We recently started using Partial Upsert tables for a use-case and started seeing this issue. We have a cluster with a few partial upsert tables with replication=1. If we restart a server in the cluster, all the tables (even offline/vanilla-realtime tables) go into Bad state.

In the server logs we see logs like the following:

```
2023/01/26 17:45:32.602 INFO [TableStateUtils] [HelixTaskExecutor-message_handle_thread_29] Find unloaded segment: my_great_table, table: my_great_table, expected: ONLINE, actual: OFFLINE
```

On taking a thread-dump I see as many threads as there are partial upsert tables in the cluster, all stuck in this loop (corresponding [PR](https://github.com/apache/pinot/pull/8923/files)):

https://github.com/apache/pinot/blob/master/pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/tablestate/TableStateUtils.java#L130

Sample thread-dump:

```
"HelixTaskExecutor-message_handle_thread_35" #116 daemon prio=5 os_prio=0 cpu=74100.46ms elapsed=3248.88s tid=0x00007eb8202b8000 nid=0xe9 waiting on condition  [0x00007eb78b8f8000]
   java.lang.Thread.State: TIMED_WAITING (sleeping)
        at java.lang.Thread.sleep(java.base@11.0.15/Native Method)
        at org.apache.pinot.segment.local.utils.tablestate.TableStateUtils.waitForAllSegmentsLoaded(TableStateUtils.java:133)
        at org.apache.pinot.core.data.manager.realtime.RealtimeTableDataManager.addSegment(RealtimeTableDataManager.java:416)
        - locked <0x00007ebbe43613b8> (a java.util.concurrent.atomic.AtomicBoolean)
        at org.apache.pinot.server.starter.helix.HelixInstanceDataManager.addRealtimeSegment(HelixInstanceDataManager.java:189)
        at org.apache.pinot.server.starter.helix.SegmentOnlineOfflineStateModelFactory$SegmentOnlineOfflineStateModel.onBecomeOnlineFromOffline(SegmentOnlineOfflineStateModelFactory.java:168)
        at org.apache.pinot.server.starter.helix.SegmentOnlineOfflineStateModelFactory$SegmentOnlineOfflineStateModel.onBecomeConsumingFromOffline(SegmentOnlineOfflineStateModelFactory.java:83)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(java.base@11.0.15/Native Method)
        at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(java.base@11.0.15/NativeMethodAccessorImpl.java:62)
        at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(java.base@11.0.15/DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(java.base@11.0.15/Method.java:566)
        at org.apache.helix.messaging.handling.HelixStateTransitionHandler.invoke(HelixStateTransitionHandler.java:350)
```

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #10185 

There is a potential deadlock in the check of all segments loaded for a table:
- Server restarts and a segment gets OFFLINE -> CONSUMING state transition
- This segment is committed and becomes ONLINE in IS
- The check will block the state transition from OFFLINE -> CONSUMING, and the check will never pass because Helix won't send another state transition to bring the segment online when there is already a pending message

The fix is to move the check out of the state transition handling, but add it into the consumption loop so that state transition is unblocked.
Also improve the log to include the segments unloaded

### CODE REVIEW

File: pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/tablestate/TableStateUtils.java [hunk 1]
```diff
@@ -83,58 +84,57 @@ public static List<String> getSegmentsInGivenStateForThisInstance(HelixManager h
...
+          tableNameWithType);
+      return false;
+    }
+    List<String> unloadedSegments = new ArrayList<>();
+    Map<String, String> currentStateMap = currentState.getPartitionStateMap();
+    for (String segmentName : onlineSegments) {
+      String actualState = currentStateMap.get(segmentName);
+      if (!SegmentStateModel.ONLINE.equals(actualState)) {
+        if (SegmentStateModel.ERROR.equals(actualState)) {
+          LOGGER.error("Found ERROR segment: {}, table: {}, expected: {}", segmentName, tableNameWithType,
```
Comment (KKcorps) [inline pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/tablestate/TableStateUtils.java:117]:
```suggestion
          LOGGER.error("Found segment: {} in ERROR state, table: {}, expected: {}", segmentName, tableNameWithType,
```

Comment (KKcorps) [reply pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/tablestate/TableStateUtils.java:117]: Also, one issue I find with such logs is, it doesn't tell what users should do. e.g. Why is the segment in ERROR state, where can they check exception etc.

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeTableDataManager.java [hunk 2]
```diff
@@ -203,6 +207,36 @@ protected void doInit() {
...
+        volatile boolean _allSegmentsLoaded = false;
+        long _lastCheckTimeNs = Long.MIN_VALUE;
+
+        @Override
+        public boolean getAsBoolean() {
+          if (_allSegmentsLoaded) {
+            return true;
+          } else {
+            synchronized (this) {
+              if (_allSegmentsLoaded) {
```
Comment (KKcorps) [inline pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeTableDataManager.java:223]: Is the check down twice (first on line 219 and then on 223) to avoid taking unnecessary lock when the variable is true?

**Review by KKcorps — APPROVED** [review]
Minor comments. LGTM otherwise!

File: pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/tablestate/TableStateUtils.java (hunk 1 above)
Comment (Jackie-Jiang) [reply pinot-segment-local/src/main/java/org/apache/pinot/segment/local/utils/tablestate/TableStateUtils.java:117]: From here we don't really know what is the cause of the ERROR state.
Good point on educate the user about how to debug. I think we should document the potential cause of ERROR state, and how to debug it in the pinot documentation.

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeTableDataManager.java (hunk 2 above)
Comment (Jackie-Jiang) [reply pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeTableDataManager.java:223]: Correct. We want to avoid lock when all segments are already loaded
