### PR TITLE
Make OOM Protection work with GRPC Queries

### LINKED ISSUE #16041: GRPC Query Tests fail when OOM Protection is enabled
Server GRPC queries are used when Pinot is used with Trino/Presto.

queryId is not set for these queries and is set to null. However the assert in the following function caused tests to fail.
```
    public void createExecutionContextInner(@Nullable String queryId, int taskId,
        ThreadExecutionContext.TaskType taskType, @Nullable ThreadExecutionContext parentContext) {
      _threadLocalEntry.get()._errorStatus.set(null);
      if (parentContext == null) {
        // is anchor thread
        assert queryId != null;
        _threadLocalEntry.get()
            .setThreadTaskStatus(queryId, CommonConstants.Accounting.ANCHOR_TASK_ID, taskType, Thread.currentThread());
      } else {
        // not anchor thread
        _threadLocalEntry.get().setThreadTaskStatus(queryId, taskId, parentContext.getTaskType(),
            parentContext.getAnchorThread());
      }
    }
```

### PR DESCRIPTION
**Pull request by vrajat**
Fix usage of OOM accounting with server GRPC queries. Server GRPC queries are used when Pinot is used with Trino/Presto.

`queryId` is not set for these queries and is set to `null`. However the assert in the following function caused tests to fail.
Another issue that `parentContext` for a worker maybe null because `setupRunner` is not called. In this case, a worker is treated as runner. However, a worker does not have a `queryId`. It is expected to be in the parentContext.

```
    public void createExecutionContextInner(@Nullable String queryId, int taskId,
        ThreadExecutionContext.TaskType taskType, @Nullable ThreadExecutionContext parentContext) {
      _threadLocalEntry.get()._errorStatus.set(null);
      if (parentContext == null) {
        // is anchor thread
        assert queryId != null;
        _threadLocalEntry.get()
            .setThreadTaskStatus(queryId, CommonConstants.Accounting.ANCHOR_TASK_ID, taskType, Thread.currentThread());
      } else {
        // not anchor thread
        _threadLocalEntry.get().setThreadTaskStatus(queryId, taskId, parentContext.getTaskType(),
            parentContext.getAnchorThread());
      }
    }
```

One option as a fix is to set query id for server GRPC queries. That task can be taken up independently.

The PR instead removes the assert and handles parameters with `null` value gracefully. _This improves resiliency of the feature because parameters maybe null if some query execution paths do not initialize the thread state_

## Deprecate createExecutionContext and replace with setup(Runner | Worker)
One of the major issues with handling nulls is that the above function uses `parentContext == null` to differentiate between runners and workers. This is not required. The caller of this function knows if it is a runner or worker. Therefore this method has been deprecated and replaced with `setupRunner` and `setupWorker`. 

## Check for nulls and skip task status initialization
`setupRunner` and `setupWorker` in `PerQueryCPUMemResourceUsageAccountant` set thread task status in `_threadEntriesMap`. If any of the metadata is `null`, then the task status is **NOT** set. With this change, accounting maybe inaccurate because the accounting modules will assume the thread is idle. The upside is that there are no NPE.

As part of the change, function parameters and return-values have been annotated with `Nullable`. 

## Remove Query Termination Logic from DefaultThreadResourceUsageAccountant

`DefaultThreadResourceUsageAccountant` maintained a thread local - `_anchorThread` that was used by a query execution thread to check if its anchor thread was cancelled _when_  `PerQueryCPUMemResourceUsageAccountant` is used. **The code is as confusing as the previous sentence.** This is not requried. The anchor thread is also available in a thread's `ThreadExecutionContext`. 

This was also the reason why `PerQueryCPUMemResourceUsageAccountant` extended `DefaultThreadResourceUsageAccountant`. After changing the code to use `ThreadExecutionContext` to get the anchor thread, the dependency can be removed and the class can directly implement `ThreadResourceUsageAccountant`.

Manual testing was done. 

Closes #16041

### CODE REVIEW

File: pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageOOMAccountingIntegrationTest.java [hunk 1]
```diff
@@ -0,0 +1,30 @@
...
+
+import org.testng.annotations.BeforeTest;
+
+
+public class OfflineGRPCServerMultiStageOOMAccountingIntegrationTest
+    extends OfflineGRPCServerOOMAccountingIntegrationTest {
+  @BeforeTest
+  void enableMultiStage() {
+    setUseMultiStageQueryEngine(true);
+  }
```
Comment (gortiz) [inline pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageOOMAccountingIntegrationTest.java]: I don't get this. IICU we cannot run MSE using GRPC server

**Review by gortiz — APPROVED** [review]

File: pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageOOMAccountingIntegrationTest.java (hunk 1 above)
Comment (vrajat) [reply pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageOOMAccountingIntegrationTest.java]: There is a similar test https://github.com/apache/pinot/blob/master/pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageIntegrationTest.java 

Am I testing the wrong GRPC end points ?

File: pinot-spi/src/main/java/org/apache/pinot/spi/trace/Tracing.java [hunk 2]
```diff
@@ -172,22 +171,23 @@ public InvocationRecording activeRecording() {
    */
   public static class DefaultThreadResourceUsageAccountant implements ThreadResourceUsageAccountant {
```
Comment (vvivekiyer) [inline pinot-spi/src/main/java/org/apache/pinot/spi/trace/Tracing.java:172]: Can we just totally remove DefaultThreadResourceUsageAccountant?

File: pinot-core/src/main/java/org/apache/pinot/core/accounting/PerQueryCPUMemAccountantFactory.java [hunk 3]
```diff
@@ -310,22 +325,26 @@ public void setThreadResourceUsageProvider(ThreadResourceUsageProvider threadRes
     }
 
     @Override
-    public void createExecutionContextInner(@Nullable String queryId, int taskId,
-        ThreadExecutionContext.TaskType taskType, @Nullable ThreadExecutionContext parentContext) {
+    public void setupRunner(@Nullable String queryId, int taskId, ThreadExecutionContext.TaskType taskType) {
```
Comment (vvivekiyer) [inline pinot-core/src/main/java/org/apache/pinot/core/accounting/PerQueryCPUMemAccountantFactory.java:328]: I understand the reasoning that GRPC queries will not have queryId. I would rather pass the queryId there than fix this functions to take null queryId.

File: pinot-spi/src/main/java/org/apache/pinot/spi/trace/Tracing.java (hunk 2 above)
Comment (vrajat) [reply pinot-spi/src/main/java/org/apache/pinot/spi/trace/Tracing.java:172]: That will be a major change and complicate this PR. However I predict that in the course of working on #16039 , this will disappear. The main complication is what to return when `Tracing.getThreadAccountant` is called.

File: pinot-core/src/main/java/org/apache/pinot/core/accounting/PerQueryCPUMemAccountantFactory.java (hunk 3 above)
Comment (vrajat) [reply pinot-core/src/main/java/org/apache/pinot/core/accounting/PerQueryCPUMemAccountantFactory.java:328]: The major work is that query id is generated in the broker. These queries are submitted to the server directly. I've created an issue for it #16059 . Regardless, its a good idea to safeguard this code ? Query id can be null because code is not instrumented, other query engines etc.

`parentContext == null` is a standard concern in MSE & SSE because instrumentation is missed. In those cases, a worker will be considered a runner rather bailing out on capturing wrong metadata.

File: pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageOOMAccountingIntegrationTest.java (hunk 1 above)
Comment (gortiz) [reply pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageOOMAccountingIntegrationTest.java]: I think that class was created during the 1.0.0 release, when we tried to test everything we could with MSE. Probably, that test is not doing anything but increasing our test times.

Comment (vrajat) [reply pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineGRPCServerMultiStageOOMAccountingIntegrationTest.java]: I've removed the test.
