### PR TITLE
[multistage]fix count star handling in v1 planner

### LINKED ISSUE #11168: [multistage][agg] count(*) return final result on leaf causes compilation error
```
select /*+ aggOptions(is_partitioned_by_group_by_keys = 'true') */
AirlineID, count(*)
from airlineStats 
group by 1
order by 2
```
causes error b/c directly the `order by` operation cannot know count(*) is a non-nullable result column thus the isNullLast check in query context compilation will fail (b/c V2 engine doesn't carry the `*` argument over to the QueryContext thus causes isNullLast check accessing operand position out of bound:
```
java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64) ~[?:?]
	at jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70) ~[?:?]
	at jdk.internal.util.Preconditions.checkIndex(Preconditions.java:248) ~[?:?]
	at java.util.Objects.checkIndex(Objects.java:372) ~[?:?]
	at java.util.ArrayList.get(ArrayList.java:459) ~[?:?]
	at org.apache.pinot.core.query.request.context.utils.QueryContextConverterUtils.isNullsLast(QueryContextConverterUtils.java:178) ~[classes/:?]
```

### PR DESCRIPTION
**Pull request by walterddr**
Fix #11168

### CODE REVIEW

File: pinot-query-planner/src/main/java/org/apache/pinot/query/parser/CalciteRexExpressionParser.java [hunk 1]
```diff
@@ -210,6 +210,10 @@ private static Expression compileFunctionExpression(RexExpression.FunctionCall r
     for (RexExpression childNode : childNodes) {
       operands.add(toExpression(childNode, pinotQuery));
     }
+    // for COUNT, add a literal val 1 to operand list b/c V1 doesn't handle empty operand functions.
+    if (functionKind == SqlKind.COUNT && operands.isEmpty()) {
+      operands.add(RequestUtils.getLiteralExpression(1));
```
Comment (Jackie-Jiang) [inline pinot-query-planner/src/main/java/org/apache/pinot/query/parser/CalciteRexExpressionParser.java:215]: To keep the existing V1 behavior, let's put `RequestUtils.getIdentifierExpression("*")`

**Review by Jackie-Jiang — APPROVED** [review]
