### PR TITLE
Fix typo in UserConfig method name - getPermissios to getPermissions

### LINKED ISSUE #17307: Add method getPermissions in UserConfig and deprecate getPermissios
Found during code review by copilot in #17295. There is typo in method name `getPermissios` in `UserConfig`. We should create a new method `getPermissions` in `UserConfig` and deprecate `getPermissios`

### PR DESCRIPTION
**Pull request by rsrkpatwari1234**
Fixes #17307
This PR addresses a typo in the method name getPermissios() found in the UserConfig class during code review. The method name has been corrected to getPermissions() with proper backward compatibility maintained.

### Backward Compatibility
✅ No breaking changes - The deprecated getPermissios() method is retained and delegates to getPermissions(), ensuring existing code continues to work.
Testing
✅ No test files required updates as they don't directly call the method
✅ All usages in the codebase have been updated to use the correct method name

`bugfix`

### CODE REVIEW

**Comment by rsrkpatwari1234** [comment]
@Jackie-Jiang Requesting your help in running the above workflow and reviewing the changes

**Comment by yashmayya** [comment]
Thanks for the fix! I'll merge once CI passes.

File: pinot-spi/src/main/java/org/apache/pinot/spi/config/user/UserConfig.java [hunk 1]
```diff
@@ -109,10 +109,18 @@ public List<String> getExcludeTables() {
...
-  public List<AccessType> getPermissios() {
+  public List<AccessType> getPermissions() {
     return _permissions;
   }
 
+  /**
+   * @deprecated Use {@link #getPermissions()} instead. This method has a typo in its name.
+   */
+  @Deprecated
+  public List<AccessType> getPermissios() {
```
Comment (Jackie-Jiang) [inline pinot-spi/src/main/java/org/apache/pinot/spi/config/user/UserConfig.java:123]: I think we'll need to add `@JsonIgnore` to this method. Same for `getUsernameWithComponent()` (not introduced in this PR).

Could you please also add a test to ensure the serialized format is as expected?

Comment (yashmayya) [reply pinot-spi/src/main/java/org/apache/pinot/spi/config/user/UserConfig.java:123]: Hm wouldn't we want to remove it from the JSON representation at the same time we remove the deprecated method?

Comment (rsrkpatwari1234) [reply pinot-spi/src/main/java/org/apache/pinot/spi/config/user/UserConfig.java:123]: The typo'd method is just for Java API backward compatibility, not JSON backward compatibility. Adding @JsonIgnore to prevent accidental JSON serialization

Comment (Jackie-Jiang) [reply pinot-spi/src/main/java/org/apache/pinot/spi/config/user/UserConfig.java:123]: Thanks for adding the test! `"usernameWithComponent"` is also mistakenly included when serializing the JSON. Let's also fix that and use the test to guard that

**Comment by rsrkpatwari1234** [comment]
Addressed all comments, requesting re-review

**Comment by rsrkpatwari1234** [comment]
Seeing below failures for one of the checks, but it does not seem related to this PR's change. Is this some known flaky tests?  
 
```
  Jan 21, 2026 4:27:44 PM org.glassfish.grizzly.http.server.NetworkListener start
  INFO: Started listener bound to [0.0.0.0:8097]
  Jan 21, 2026 4:27:44 PM org.glassfish.grizzly.http.server.HttpServer start
  INFO: [HttpServer] Started.
  2026/01/21 16:27:44.864 INFO [StartServiceManagerCommand] [Start a Pinot [SERVER]] Started Pinot [SERVER] instance [Server_10.1.0.204_8098] at 41.275s since launch
  Cluster stopped.
  Failed after server 2 downgrade
  + rc=1
```
