### PR TITLE
Modify segment metadata call

### LINKED ISSUE #13990: Pinot Controller leader re-election not triggered
We faced an issue in production wherein the controller leader node went down but re-election was not triggered. This lead to segment upload errors for tables trying to commit a segment, instances being marked as unavailable for the segment and finally queries failing for the tables with segments unavailable error. 
Pinot version - 1.0.x

Timeline for this was as follows:
1. A GET call for a large table's segments' metadata `tables/<tablename>/segments/<segmentName>/metadata?columns=*` spawns ~75k threads. This cause a huge memory spike and heap to go out of memory (heap size being 128GB here), maybe crashing the node. We suspect it was because of reload status button which triggers the segment metadata call
Screenshot 2024-09-12 at 7 11 38 PM

2. The node's 2 zk sessions time out at 17:19:56, the node tries to reestablish connection but it keeps emitting metrics as a leader until 17:29:x
Screenshot 2024-09-12 at 7 11 05 PM

3. The health check for node starts failing around 17:20:x, but standby controller nodes keep polling and getting failed leader's session ID as leader until 18:10 when we triggered a force replacement of error node
Screenshot 2024-09-12 at 7 19 24 PM

```
Instance 123 is not leader of cluster production-cluster due to current session 702147796290178 does not match leader session 702147796290171
```

Ideally the re-election should've triggered around 17:20.

### PR DESCRIPTION
**Pull request by cypherean**
Fixes #13990 
The fetch segment metadata call for a table makes one call per segment, instead we can have one call per server

### CODE REVIEW

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 1]
```diff
@@ -840,6 +841,36 @@ public String getServerMetadata(
     return segmentsMetadata;
   }
 
+  @GET
+  @Path("segments/{tableName}/metadataV2")
+  @Authorize(targetType = TargetType.TABLE, paramName = "tableName", action = Actions.Table.GET_METADATA)
+  @Produces(MediaType.APPLICATION_JSON)
+  @ApiOperation(value = "Get the server metadata for all table segments",
+      notes = "Get the server metadata for all table segments")
+  public String getServerSegmentsMetadata(
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java:850]: What is the difference between this one and the original one?

Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java:850]: It makes one call per server whereas `segments/{tableName}/metadata` makes 1 call per segment to fetch the metadata

Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java:941]: Am I mis-reading? Seems this one is exactly the same as the deprecated one

Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: Added the necessary changes. The new API is added for backward compatibility instead of modifying the old one. They call different functions and table resource API.

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 2]
```diff
@@ -114,7 +114,7 @@
  *       <li>"/segments/{tableName}/servers": get a map from server to segments hosted by the server</li>
  *       <li>"/segments/{tableName}/crc": get a map from segment to CRC of the segment (OFFLINE table only)</li>
  *       <li>"/segments/{tableName}/{segmentName}/metadata: get the metadata for a segment</li>
- *       <li>"/segments/{tableName}/metadata: get the metadata for all segments from the server</li>
+ *       <li>"/v2/segments/{tableName}/metadata: get the metadata for all/included segments from the server</li>
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java:117]: We shouldn't need to introduce this new API. We can just add an extra query parameter for segments

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 3]
```diff
@@ -931,6 +933,37 @@ public String getServerMetadata(
...
+  @Path("v2/segments/{tableName}/metadata")
+  @Authorize(targetType = TargetType.TABLE, paramName = "tableName", action = Actions.Table.GET_METADATA)
+  @Produces(MediaType.APPLICATION_JSON)
+  @ApiOperation(value = "Get the server metadata for all table segments",
+      notes = "Get the server metadata for all table segments")
+  public String getServerMetadata(
+      @ApiParam(value = "Name of the table", required = true) @PathParam("tableName") String tableName,
+      @ApiParam(value = "OFFLINE|REALTIME") @QueryParam("type") String tableTypeStr,
+      @ApiParam(value = "Columns name", allowMultiple = true) @QueryParam("columns")
+      List<String> columns, @ApiParam(value = "Segments name", allowMultiple = true) @QueryParam("segmentsToInclude")
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java:946]: Suggest naming the query parameter `"segments"` to be more concise

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 4]
```diff
@@ -442,6 +442,14 @@ private String generateSegmentMetadataServerURL(String tableNameWithType, String
     return String.format("%s/tables/%s/segments/%s/metadata?%s", endpoint, tableNameWithType, segmentName, paramsStr);
   }
 
+  public String generateTableMetadataServerURL(String tableNameWithType, List<String> columns,
+                                               Set<String> segmentsToInclude, String endpoint) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java:446]: (format) Please reformat the changes

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java (hunk 3 above)
Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java:946]: Without default value, will `columns` and `segmentsToInclude` be nullable? If so, let's annotate them as `@Nullable`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 5]
```diff
@@ -84,11 +85,46 @@ public List<String> getReloadCheckResponses(String tableNameWithType, int timeou
...
+   * This calls the server to get the metadata for all segments instead of making a call per segment.
    */
   public JsonNode getSegmentsMetadata(String tableNameWithType, List<String> columns, Set<String> segmentsToInclude,
       int timeoutMs)
       throws InvalidConfigException, IOException {
-    return getSegmentsMetadataInternal(tableNameWithType, columns, segmentsToInclude, timeoutMs);
+    return getSegmentsMetadataInternalV2(tableNameWithType, columns, segmentsToInclude, timeoutMs);
+  }
+
+  private JsonNode getSegmentsMetadataInternalV2(String tableNameWithType, List<String> columns,
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java:96]: Let's modify the `getSegmentsMetadataInternal()` to first try the new API, and fallback to the old way if the new API doesn't work (e.g. server still runs old version)

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 6]
```diff
@@ -118,7 +118,7 @@
  *       <li>"/segments/{tableName}/servers": get a map from server to segments hosted by the server</li>
  *       <li>"/segments/{tableName}/crc": get a map from segment to CRC of the segment (OFFLINE table only)</li>
  *       <li>"/segments/{tableName}/{segmentName}/metadata: get the metadata for a segment</li>
- *       <li>"/segments/{tableName}/metadata: get the metadata for all segments from the server</li>
+ *       <li>"/segments/{tableName}/metadata</li>
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: Why removing the description?

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 7]
```diff
@@ -926,7 +926,8 @@ public String getServerMetadata(
       @ApiParam(value = "Name of the table", required = true) @PathParam("tableName") String tableName,
       @ApiParam(value = "OFFLINE|REALTIME") @QueryParam("type") String tableTypeStr,
       @ApiParam(value = "Columns name", allowMultiple = true) @QueryParam("columns") @DefaultValue("")
-          List<String> columns, @Context HttpHeaders headers) {
+      List<String> columns, @ApiParam(value = "Segments name", allowMultiple = true) @QueryParam("segments")
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: (minor) Put it in the next line for readability

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 8]
```diff
@@ -1162,7 +1163,25 @@ private JsonNode getSegmentsMetadataFromServer(String tableNameWithType, List<St
     TableMetadataReader tableMetadataReader =
         new TableMetadataReader(_executor, _connectionManager, _pinotHelixResourceManager);
     return tableMetadataReader
-        .getSegmentsMetadata(tableNameWithType, columns, _controllerConf.getServerAdminRequestTimeoutSeconds() * 1000);
+        .getSegmentsMetadata(tableNameWithType, columns,
+            _controllerConf.getServerAdminRequestTimeoutSeconds() * 1000);
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: (minor) Revert this change

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java (hunk 7 above)
Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: (minor) To be consistent with `getSegmentMetadata`, let's put `segments` in front of `columns`. Same for other method signatures

Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: Do we need to decode the segment names?

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java (hunk 8 above)
Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: Is this method still in use?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 9]
```diff
@@ -127,40 +128,108 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
-    }
-    return JsonUtils.objectToJsonNode(response);
+    // legacy per segment endpoint
+    List<String> segmentUrls = buildSegmentLevelUrls(serverToSegs, endpoints,
+        tableNameWithType, columns, segmentsToInclude, reader);
+    return fetchAndAggregateMetadata(segmentUrls, endpoints.inverse(), /*perSegmentJson=*/true,
+        tableNameWithType, timeoutMs);
   }
 
   /**
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java:228]: We can remove this method

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java [hunk 10]
```diff
@@ -402,6 +403,62 @@ public String getSegmentMetadata(
...
+  @ApiOperation(value = "Provide segments metadata", notes = "Provide segments metadata for the segments on server")
+  @ApiResponses(value = {
+      @ApiResponse(code = 200, message = "Success"),
+      @ApiResponse(code = 500, message = "Internal server error", response = ErrorInfo.class),
+      @ApiResponse(code = 404, message = "Table or segment not found", response = ErrorInfo.class)
+  })
+  public String getSegmentsMetadata(
+      @ApiParam(value = "Table name including type", required = true, example = "myTable_OFFLINE")
+      @PathParam("tableName") String tableName,
+      @ApiParam(value = "Segment names to include", allowMultiple = true) @QueryParam("segmentsToInclude")
```
Comment (Jackie-Jiang) [inline pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java]: (minor)
```suggestion
      @ApiParam(value = "Segment names to include", allowMultiple = true) @QueryParam("segments")
```

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java [hunk 11]
```diff
@@ -402,6 +403,62 @@ public String getSegmentMetadata(
...
+      @DefaultValue("") List<String> segmentsToInclude,
+      @ApiParam(value = "Column name", allowMultiple = true) @QueryParam("columns") @DefaultValue("")
+      List<String> columns, @Context HttpHeaders headers) {
+    tableName = DatabaseUtils.translateTableName(tableName, headers);
+    TableDataManager tableDataManager = ServerResourceUtils.checkGetTableDataManager(_serverInstance, tableName);
+    // decode columns and segments
+    List<String> decodedSegments = new ArrayList<>();
+    if (segmentsToInclude != null && !segmentsToInclude.isEmpty()) {
```
Comment (Jackie-Jiang) [inline pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java]: (minor) Use `CollectionUtils.isNotEmpty()`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 12]
```diff
@@ -127,40 +128,108 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
+    CompletionServiceHelper cs =
+        new CompletionServiceHelper(_executor, _connectionManager, endpoints);
+    CompletionServiceHelper.CompletionServiceResponse resp =
+        cs.doMultiGetRequest(urls, tableNameWithType, perSegmentJson, timeoutMs);
+
+    if (resp._failedResponseCount == urls.size()) {
+      throw new InvalidConfigException("All requests to server instances failed.");
+    }
+
+    Map<String, JsonNode> aggregated = new HashMap<>();
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: If we are going to return a json object in the end, we can probably directly create an `ObjectNode` here

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 13]
```diff
@@ -925,8 +925,10 @@ private void deleteSegmentsInternal(String tableNameWithType, List<String> segme
   public String getServerMetadata(
       @ApiParam(value = "Name of the table", required = true) @PathParam("tableName") String tableName,
       @ApiParam(value = "OFFLINE|REALTIME") @QueryParam("type") String tableTypeStr,
+      @ApiParam(value = "Segments name", allowMultiple = true) @QueryParam("segments")
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: Do you need to assign a default value to it? If it can be `null`, then let's add `@Nullable` annotation to it. Also, does the framework support directly constructing a `Set`? Do we have a test with multiple segments?

```suggestion
      @ApiParam(value = "Segments to include", allowMultiple = true) @QueryParam("segments")
```

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 14]
```diff
@@ -127,50 +130,111 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
+    ServerSegmentMetadataReader reader =
+        new ServerSegmentMetadataReader(_executor, _connectionManager);
+
+    // try table level endpoint first
+    try {
+      List<String> tableUrls = buildTableLevelUrls(serverToSegs, endpoints,
+          tableNameWithType, columns, segmentsToInclude, reader);
+      return fetchAndAggregateMetadata(tableUrls, endpoints, /*perSegmentJson=*/false,
+          tableNameWithType, timeoutMs);
+    } catch (InvalidConfigException ignore) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: Will `fetchAndAggregateMetadata()` throw other exceptions? Should we catch `Exception` here instead?

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java [hunk 15]
```diff
@@ -402,6 +404,62 @@ public String getSegmentMetadata(
...
+  @ApiOperation(value = "Provide segments metadata", notes = "Provide segments metadata for the segments on server")
+  @ApiResponses(value = {
+      @ApiResponse(code = 200, message = "Success"),
+      @ApiResponse(code = 500, message = "Internal server error", response = ErrorInfo.class),
+      @ApiResponse(code = 404, message = "Table or segment not found", response = ErrorInfo.class)
+  })
+  public String getSegmentsMetadata(
+      @ApiParam(value = "Table name including type", required = true, example = "myTable_OFFLINE")
+      @PathParam("tableName") String tableName,
+      @ApiParam(value = "Segment names to include", allowMultiple = true) @QueryParam("segments")
```
Comment (Jackie-Jiang) [inline pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java]: (minor)
```suggestion
      @ApiParam(value = "Segments to include", allowMultiple = true) @QueryParam("segments")
```

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 16]
```diff
@@ -506,6 +513,19 @@ private String generateStaleSegmentsServerURL(String tableNameWithType, String e
...
   }
 
+  private String generateSegmentsParam(Set<String> values) {
+    String paramsStr = "";
+    if (values == null || values.isEmpty()) {
+      return paramsStr;
+    }
+    List<String> params = new ArrayList<>(values.size());
+    for (String value : values) {
+      params.add(String.format("segmentsToInclude=%s", value));
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: Is this correct? On the server side, seems the parameter is `segments`. Do you have a test for this?
I prefer `segments` over `segmentsToInclude`

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java (hunk 7 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: This is in sync with the column arg, where the params are decoded only once in the servers. Do you think we need to decode it here?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java (hunk 14 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: `fetchAndAggregateMetadata()` throw `InvalidConfigException` when all server requests fail which is expected when new server API doesn't exist. We ignore and fallback to the legacy API in this case. 
The function also throws `IOException` when stringToJsonNode conversion fails. This exception is not caught and propagated as is.

Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: `InvalidConfigException` is thrown only when it fails to read the server admin endpoint. If server doesn't support this API, I believe it can through a different exception, and break the API. Can you try removing the server side change and see if this method can correctly fall back to the old API?

Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: Verified that it falls to `InvalidConfigException` after removing the server side API and falls back to the old API
Screenshot 2025-07-10 at 11 08 01 AM

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 17]
```diff
@@ -919,15 +919,18 @@ private void deleteSegmentsInternal(String tableNameWithType, List<String> segme
 
   @GET
   @Path("segments/{tableName}/metadata")
+  @Encoded
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: I think we usually put this annotation in front of the argument. Do we want to annotate the entire method?

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 18]
```diff
@@ -1156,14 +1159,17 @@ public List<Map<TableType, List<String>>> getSelectedSegments(
    * This is a helper method to get the metadata for all segments for a given table name.
    * @param tableNameWithType name of the table along with its type
    * @param columns name of the columns
+   * @param segments name of the segments to include in metadata
    * @return Map<String, String>  metadata of the table segments -> map of segment name to its metadata
    */
-  private JsonNode getSegmentsMetadataFromServer(String tableNameWithType, List<String> columns)
+  private JsonNode getSegmentsMetadataFromServer(String tableNameWithType, List<String> columns,
+      Set<String> segments)
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: (minor) Annotate both `columns` and `segments` as `@Nullable`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 19]
```diff
@@ -127,50 +130,104 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
 
   /**
    * This api takes in list of segments for which we need the metadata.
+   * This calls the server to get the metadata for all segments instead of making a call per segment.
    */
-  public JsonNode getSegmentsMetadata(String tableNameWithType, List<String> columns, Set<String> segmentsToInclude,
+  public JsonNode getSegmentsMetadata(String tableNameWithType, List<String> columns, Set<String> segments,
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: (minor) Annotate both `columns` and `segments` as `@Nullable`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 20]
```diff
@@ -127,50 +130,104 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
       int timeoutMs)
       throws InvalidConfigException, IOException {
-    return getSegmentsMetadataInternal(tableNameWithType, columns, segmentsToInclude, timeoutMs);
+    return getSegmentsMetadataInternal(tableNameWithType, columns, segments, timeoutMs);
   }
 
-  private JsonNode getSegmentsMetadataInternal(String tableNameWithType, List<String> columns,
-      Set<String> segmentsToInclude, int timeoutMs)
+  /**
+   *   Common helper used by both the new (server-level) and legacy (segment-level) endpoints.
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: (minor) Remove extra space
```suggestion
   * Common helper used by both the new (server-level) and legacy (segment-level) endpoints.
```

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java (hunk 13 above)
Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: (minor) Suggest changing the value to `"Segments to include"`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 21]
```diff
@@ -127,50 +130,104 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
-        _pinotHelixResourceManager.getServerToSegmentsMap(tableNameWithType);
-    BiMap<String, String> endpoints =
-        _pinotHelixResourceManager.getDataInstanceAdminEndpoints(serverToSegmentsMap.keySet());
-    ServerSegmentMetadataReader serverSegmentMetadataReader =
-        new ServerSegmentMetadataReader(_executor, _connectionManager);
+    CompletionServiceHelper cs = new CompletionServiceHelper(_executor, _connectionManager, endpoints);
+    CompletionServiceHelper.CompletionServiceResponse resp =
+        cs.doMultiGetRequest(urls, tableNameWithType, perSegmentJson, timeoutMs);
+    // all requests will fail if new server endpoint is not available
+    if (resp._failedResponseCount == urls.size()) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: This is not robust. What if some servers succeed and others fail? E.g. some servers are running new code and some servers are running old code?
We should use the table level API only when all servers responded

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 22]
```diff
@@ -127,50 +130,104 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
+    return getSegmentsMetadataInternal(tableNameWithType, columns, segments, timeoutMs);
   }
 
-  private JsonNode getSegmentsMetadataInternal(String tableNameWithType, List<String> columns,
-      Set<String> segmentsToInclude, int timeoutMs)
+  /**
+   *   Common helper used by both the new (server-level) and legacy (segment-level) endpoints.
+   */
+  private JsonNode fetchAndAggregateMetadata(List<String> urls,
+      BiMap<String, String> endpoints,
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: (minor, format) We don't usually put parameters into multiple lines. Same for other methods

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 23]
```diff
@@ -127,50 +130,104 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
-    BiMap<String, String> endpoints =
-        _pinotHelixResourceManager.getDataInstanceAdminEndpoints(serverToSegmentsMap.keySet());
-    ServerSegmentMetadataReader serverSegmentMetadataReader =
-        new ServerSegmentMetadataReader(_executor, _connectionManager);
+    CompletionServiceHelper cs = new CompletionServiceHelper(_executor, _connectionManager, endpoints);
+    CompletionServiceHelper.CompletionServiceResponse resp =
+        cs.doMultiGetRequest(urls, tableNameWithType, perSegmentJson, timeoutMs);
+    // all requests will fail if new server endpoint is not available
+    if (resp._failedResponseCount == urls.size()) {
+      throw new InvalidConfigException("All requests to server instances failed.");
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: This shouldn't be `InvalidConfigException`. Probably a `RuntimeException`

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java (hunk 17 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: We don't need it ideally because special characters and spaces are not allowed in the params. 
The offline table in test had spaces in segment names, I can fix that instead.

For now, I'll mark segments and columns as encoded as we decode them in both metadata functions in TablesResource.

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java (hunk 13 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: We have a test with multiple segments - https://github.com/apache/pinot/pull/14250/files#diff-d6dcbeacc7de3df22db996b8d1c08fd6bf90939d4a42d8a1c019f626d241e244R128

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java (hunk 21 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: Checking for failure > 0 now and throws a runtime exception which is caught and ignored to fallback to legacy

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 24]
```diff
@@ -434,14 +434,21 @@ private String generateAggregateSegmentMetadataServerURL(String tableNameWithTyp
     return String.format("%s/tables/%s/metadata?%s", endpoint, tableNameWithType, paramsStr);
   }
 
-  private String generateSegmentMetadataServerURL(String tableNameWithType, String segmentName, List<String> columns,
+  public String generateSegmentMetadataServerURL(String tableNameWithType, String segmentName, List<String> columns,
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: Annotate `columns` as `@Nullable`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 25]
```diff
@@ -434,14 +434,21 @@ private String generateAggregateSegmentMetadataServerURL(String tableNameWithTyp
...
       String endpoint) {
     tableNameWithType = URLEncoder.encode(tableNameWithType, StandardCharsets.UTF_8);
     segmentName = URLEncoder.encode(segmentName, StandardCharsets.UTF_8);
     String paramsStr = generateColumnsParam(columns);
     return String.format("%s/tables/%s/segments/%s/metadata?%s", endpoint, tableNameWithType, segmentName, paramsStr);
   }
 
+  public String generateTableMetadataServerURL(String tableNameWithType, List<String> columns,
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: Annotate both `columns` and `segmentsToInclude` as `@Nullable`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 26]
```diff
@@ -434,14 +434,21 @@ private String generateAggregateSegmentMetadataServerURL(String tableNameWithTyp
...
+      Set<String> segmentsToInclude, String endpoint) {
+    tableNameWithType = URLEncoder.encode(tableNameWithType, StandardCharsets.UTF_8);
+    String paramsStr = generateColumnsParam(columns) + generateSegmentsParam(segmentsToInclude);
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: If there are both columns and segmentsToInclude, do we need to connect them with `&`? We should add a test for it

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 27]
```diff
@@ -506,6 +513,19 @@ private String generateStaleSegmentsServerURL(String tableNameWithType, String e
     return String.format("%s/tables/%s/segments/isStale", endpoint, tableNameWithType);
   }
 
+  private String generateSegmentsParam(Set<String> values) {
+    String paramsStr = "";
+    if (values == null || values.isEmpty()) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: (minor)
```suggestion
    if (CollectionUtils.isEmpty(values)) {
```

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 28]
```diff
@@ -506,6 +513,19 @@ private String generateStaleSegmentsServerURL(String tableNameWithType, String e
...
+      return paramsStr;
+    }
+    List<String> params = new ArrayList<>(values.size());
+    for (String value : values) {
+      params.add(String.format("segments=%s", value));
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: Avoid using `String.format()` and directly use `"segments=" + value`

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 29]
```diff
@@ -506,6 +513,19 @@ private String generateStaleSegmentsServerURL(String tableNameWithType, String e
     return String.format("%s/tables/%s/segments/isStale", endpoint, tableNameWithType);
   }
 
+  private String generateSegmentsParam(Set<String> values) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: We can consider passing `prefix` (`"columns="` or `"segments="`) so that the same method can be reused by both columns and segments

Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: nit: values -> segments?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java (hunk 26 above)
Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: has this been tested with a very large number of segments (like 75K+ mentioned in the issue)? Are there concerns with the request URL getting too big?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 30]
```diff
@@ -127,50 +131,93 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
+        new ServerSegmentMetadataReader(_executor, _connectionManager);
+
+    // try table level endpoint first
+    try {
+      List<String> tableUrls = buildTableLevelUrls(serverToSegs, endpoints,
+          tableNameWithType, columns, segments, reader);
+      return fetchAndAggregateMetadata(tableUrls, endpoints, /*perSegmentJson=*/false,
+          tableNameWithType, timeoutMs);
+    } catch (RuntimeException ignore) {
+      // fall through to legacy
```
Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: nit: can a warning be logged here?

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java [hunk 31]
```diff
@@ -409,6 +411,62 @@ public String getSegmentMetadata(
     }
   }
 
+  @GET
+  @Encoded
+  @Path("/tables/{tableName}/segments/metadata")
```
Comment (somandal) [inline pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java:417]: Just wondering if it makes sense to special case the scenario where we want to fetch ALL segments (like what's expected in the API call), where we don't pass a segment list and instead return all segments? That would keep the params short as well 

cc @Jackie-Jiang any thoughts on the above as well?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java [hunk 32]
```diff
@@ -127,50 +131,93 @@ private TableReloadJsonResponse processSegmentMetadataReloadResponse(
...
-    BiMap<String, String> endpoints =
-        _pinotHelixResourceManager.getDataInstanceAdminEndpoints(serverToSegmentsMap.keySet());
-    ServerSegmentMetadataReader serverSegmentMetadataReader =
-        new ServerSegmentMetadataReader(_executor, _connectionManager);
+    CompletionServiceHelper cs = new CompletionServiceHelper(_executor, _connectionManager, endpoints);
+    CompletionServiceHelper.CompletionServiceResponse resp =
+        cs.doMultiGetRequest(urls, tableNameWithType, perSegmentJson, timeoutMs);
+    // all requests will fail if new server endpoint is not available
+    if (resp._failedResponseCount > 0) {
+      throw new RuntimeException("All requests to server instances failed.");
```
Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: question: is it not possible at all to get partial results, where some servers return some data but others fail? or are you treating it as failed if even one server fails to return a response?

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java (hunk 31 above)
Comment (Jackie-Jiang) [reply pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java:417]: I believe that's the behavior when `segments` is not provided

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java [hunk 33]
```diff
@@ -409,6 +411,62 @@ public String getSegmentMetadata(
...
+  @ApiResponses(value = {
+      @ApiResponse(code = 200, message = "Success"),
+      @ApiResponse(code = 500, message = "Internal server error", response = ErrorInfo.class),
+      @ApiResponse(code = 404, message = "Table or segment not found", response = ErrorInfo.class)
+  })
+  public String getSegmentsMetadata(
+      @ApiParam(value = "Table name including type", required = true, example = "myTable_OFFLINE")
+      @PathParam("tableName") String tableName,
+      @ApiParam(value = "Segments name", allowMultiple = true) @QueryParam("segments")
+      @DefaultValue("") List<String> segments,
```
Comment (Jackie-Jiang) [inline pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java]: Should we also annotate this as `@Nullable`? Same for `columns`

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java (hunk 31 above)
Comment (somandal) [reply pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java:417]: yes, that's right, never mind this comment. I see we allow the segments field to be nullable, which is equivalent to fetching all segments

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java [hunk 34]
```diff
@@ -409,6 +411,62 @@ public String getSegmentMetadata(
...
+        String segmentMetadata = SegmentMetadataFetcher.getSegmentMetadata(segmentDataManager, columns);
+        JsonNode segmentMetadataJson = JsonUtils.stringToJsonNode(segmentMetadata);
+        response.put(segmentName, segmentMetadataJson);
+      } catch (Exception e) {
+        LOGGER.error("Failed to convert table {} segment {} to json", tableName, segmentName);
+        throw new WebApplicationException("Failed to convert segment metadata to json",
+            Response.Status.INTERNAL_SERVER_ERROR);
+      } finally {
+        tableDataManager.releaseSegment(segmentDataManager);
+      }
```
Comment (somandal) [inline pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java]: won't this leave some of the `segmentDataManager` unreleased, if an exception is thrown while processing one?

Perhaps instead we should put the whole for loop under try-catch and release everything at one go at the end?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java (hunk 29 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: Just updated it to a generic function to construct params, keeping the arg name as values for now

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java (hunk 34 above)
Comment (cypherean) [reply pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java]: good catch, thanks

File: pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java (hunk 33 above)
Comment (cypherean) [reply pinot-server/src/main/java/org/apache/pinot/server/api/resources/TablesResource.java:428]: Here we've set a default value "" which should be fine since we don't do any post processing after this unlike the controller where we create URLs. 

Let me run it locally once again and get back to you on the exact behaviour when default value is string in list args, it takes it as a single entry in the list afair

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java (hunk 32 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: We're treating it as failed as it could be due to partially rolled out server side changes and this maintains the backward compatibility. This was pointed out by @Jackie-Jiang sometime back in this PR

Comment (somandal) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: should the message be updated here to say something like "Got %d failed responses from total %d server instances" instead? this sounds misleading that all requests have failed, when a subset may have failed.

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 35]
```diff
@@ -488,24 +496,24 @@ private Pair<String, String> generateValidDocIdsMetadataURL(String tableNameWith
     return Pair.of(url, jsonTableSegments);
   }
 
-  private String generateColumnsParam(List<String> columns) {
+  private String generateStaleSegmentsServerURL(String tableNameWithType, String endpoint) {
+    tableNameWithType = URLEncoder.encode(tableNameWithType, StandardCharsets.UTF_8);
+    return String.format("%s/tables/%s/segments/isStale", endpoint, tableNameWithType);
+  }
+
+  private String generateParam(List<String> values, String key) {
```
Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: nit: can we reorder the parameters, key first and then values?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java [hunk 36]
```diff
@@ -430,18 +431,25 @@ public Map<String, TableStaleSegmentResponse> getStaleSegmentsFromServer(
...
     segmentName = URLEncoder.encode(segmentName, StandardCharsets.UTF_8);
-    String paramsStr = generateColumnsParam(columns);
+    String paramsStr = generateParam(columns, "columns");
     return String.format("%s/tables/%s/segments/%s/metadata?%s", endpoint, tableNameWithType, segmentName, paramsStr);
   }
 
+  public String generateTableMetadataServerURL(String tableNameWithType, @Nullable List<String> columns,
+      @Nullable List<String> segmentsToInclude, String endpoint) {
+    tableNameWithType = URLEncoder.encode(tableNameWithType, StandardCharsets.UTF_8);
+    String paramsStr = generateParam(columns, "columns") + generateParam(segmentsToInclude, "segments");
```
Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/util/ServerSegmentMetadataReader.java]: nit: "columns" is used in a couple of places, can you add constants for "columns" and "segments" instead?

File: pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java (hunk 32 above)
Comment (cypherean) [reply pinot-controller/src/main/java/org/apache/pinot/controller/util/TableMetadataReader.java]: updated

**Review by somandal — APPROVED** [review]
lgtm!
@Jackie-Jiang do you want to do a final pass before merging? thanks!

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 37]
```diff
@@ -926,8 +926,10 @@ private void deleteSegmentsInternal(String tableNameWithType, List<String> segme
   public String getServerMetadata(
       @ApiParam(value = "Name of the table", required = true) @PathParam("tableName") String tableName,
       @ApiParam(value = "OFFLINE|REALTIME") @QueryParam("type") String tableTypeStr,
-      @ApiParam(value = "Columns name", allowMultiple = true) @QueryParam("columns") @DefaultValue("")
-          List<String> columns, @Context HttpHeaders headers) {
+      @Encoded @ApiParam(value = "Segments to include", allowMultiple = true) @QueryParam("segments")
```
Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: nit: should we call out that if this is empty, it fetches for all segments?

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java [hunk 38]
```diff
@@ -926,8 +926,10 @@ private void deleteSegmentsInternal(String tableNameWithType, List<String> segme
...
+      @Nullable List<String> segments,
+      @Encoded @ApiParam(value = "Columns name", allowMultiple = true) @QueryParam("columns")
+      @Nullable List<String> columns, @Context HttpHeaders headers) {
     tableName = DatabaseUtils.translateTableName(tableName, headers);
     LOGGER.info("Received a request to fetch metadata for all segments for table {}", tableName);
```
Comment (somandal) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotSegmentRestletResource.java]: nit: should this be updated to call out "all segments" only if segments is empty? and otherwise log the number of segments?

**Review by somandal — COMMENTED** [review]
oops, couple of small nits i forgot to add earlier
