### PR TITLE
Fix for #12133 - add context and proper logging framework to OsCheck output

### LINKED ISSUE #12133: improve context of logging statement that prints out OS name during service statup
the class `OsCheck` prints the value of the `os.name` system property directly to log using `System.out`.  I think this should use a proper logger and provide some additional detail instead of simply printing the system property value.

### PR DESCRIPTION
**Pull request by timveil**
The visibility of the 'detectedOS' field in the OsCheck class has been changed from protected to private. Moreover, the system output was replaced with a logger for error debugging and tracking.  Instead of simply printing the 'os.name' value to the System.out, additional context has been added to the logging statement.  Fixes #12133

### CODE REVIEW

File: pinot-core/src/main/java/org/apache/pinot/core/util/OsCheck.java [hunk 1]
```diff
@@ -46,9 +48,11 @@ public enum OSType {
     Windows, MacOS, Linux, Other
   }
 
+  private static final Logger log = LoggerFactory.getLogger(OsCheck.class);
```
Comment (Jackie-Jiang) [inline pinot-core/src/main/java/org/apache/pinot/core/util/OsCheck.java:51]: (convention) Use all uppercase for static final fields, suggest also fixing `_detectedOS` to `DETECTED_OS` or `OS_TYPE`
```suggestion
  private static final Logger LOGGER = LoggerFactory.getLogger(OsCheck.class);
```

File: pinot-core/src/main/java/org/apache/pinot/core/util/OsCheck.java [hunk 2]
```diff
@@ -46,9 +48,11 @@ public enum OSType {
...
+
   static {
     String os = System.getProperty("os.name", "generic").toLowerCase(Locale.ENGLISH);
-    System.out.println(os);
+    log.info("System property \"os.name\" is [{}]", os);
```
Comment (Jackie-Jiang) [inline pinot-core/src/main/java/org/apache/pinot/core/util/OsCheck.java:55]: @jasperjiaguo Is this print intentional?

(minor, convention)
```suggestion
    log.info("System property \"os.name\" is: {}", os);
```

**Review by Jackie-Jiang — APPROVED** [review]
