### PR TITLE
Fix multiple consecutive Exchange returning empty response

### LINKED ISSUE #11880: [multistage] mailbox receiving stage not correctly created
running the following with colocated join
```
explain implementation plan for
-- explain plan for
WITH tmp2 AS (
  SELECT * FROM userGroups
  WHERE groupUUID NOT IN ('group-3', 'group-4')
),
tmp3 AS (
  SELECT *
  FROM userAttributes
  WHERE userUUID IN (SELECT userUUID FROM tmp2)
    AND totalTrips < 100
)
SELECT * FROM tmp3 WHERE userUUID IN (SELECT userUUID from tmp2)
```
produces this physical plan:
```
[0]@100.114.228.138:50723 MAIL_RECEIVE(BROADCAST_DISTRIBUTED)
├── [1]@100.114.228.138:50752 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[0]@100.114.228.138@{50723,50723}|[0]} (Subtree Omitted)
├── [1]@100.114.228.138:50746 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[0]@100.114.228.138@{50723,50723}|[0]} (Subtree Omitted)
├── [1]@100.114.228.138:50737 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[0]@100.114.228.138@{50723,50723}|[0]} (Subtree Omitted)
└── [1]@100.114.228.138:50731 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[0]@100.114.228.138@{50723,50723}|[0]}
    └── [1]@100.114.228.138:50731 JOIN
        ├── [1]@100.114.228.138:50731 MAIL_RECEIVE(HASH_DISTRIBUTED)
        │   ├── [2]@100.114.228.138:50752 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]} (Subtree Omitted)
        │   ├── [2]@100.114.228.138:50746 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]} (Subtree Omitted)
        │   ├── [2]@100.114.228.138:50737 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]} (Subtree Omitted)
        │   └── [2]@100.114.228.138:50731 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]}
------ This receiving stage should indicate a receiving stage of [2] not [1] ------
        │       └── [1]@100.114.228.138:50731 MAIL_RECEIVE(HASH_DISTRIBUTED). 
        │           ├── [3]@100.114.228.138:50746 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]}
        │           │   └── [3]@100.114.228.138:50746 JOIN
        │           │       ├── [3]@100.114.228.138:50746 PROJECT
        │           │       │   └── [3]@100.114.228.138:50746 FILTER
        │           │       │       └── [3]@100.114.228.138:50746 TABLE SCAN (userAttributes) null
        │           │       └── [3]@100.114.228.138:50746 MAIL_RECEIVE(BROADCAST_DISTRIBUTED)
        │           │           ├── [4]@100.114.228.138:50746 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[3]@100.114.228.138@{50746,50747}|[1],[3]@100.114.228.138@{50731,50732}|[0]}
        │           │           │   └── [4]@100.114.228.138:50746 PROJECT
        │           │           │       └── [4]@100.114.228.138:50746 FILTER
        │           │           │           └── [4]@100.114.228.138:50746 TABLE SCAN (userGroups) null
        │           │           └── [4]@100.114.228.138:50731 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[3]@100.114.228.138@{50746,50747}|[1],[3]@100.114.228.138@{50731,50732}|[0]}
        │           │               └── [4]@100.114.228.138:50731 PROJECT
        │           │                   └── [4]@100.114.228.138:50731 FILTER
        │           │                       └── [4]@100.114.228.138:50731 TABLE SCAN (userGroups) null
        │           └── [3]@100.114.228.138:50731 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]}
        │               └── [3]@100.114.228.138:50731 JOIN
        │                   ├── [3]@100.114.228.138:50731 PROJECT
        │                   │   └── [3]@100.114.228.138:50731 FILTER
        │                   │       └── [3]@100.114.228.138:50731 TABLE SCAN (userAttributes) null
        │                   └── [3]@100.114.228.138:50731 MAIL_RECEIVE(BROADCAST_DISTRIBUTED)
        │                       ├── [4]@100.114.228.138:50746 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[3]@100.114.228.138@{50746,50747}|[1],[3]@100.114.228.138@{50731,50732}|[0]}
        │                       │   └── [4]@100.114.228.138:50746 PROJECT
        │                       │       └── [4]@100.114.228.138:50746 FILTER
        │                       │           └── [4]@100.114.228.138:50746 TABLE SCAN (userGroups) null
        │                       └── [4]@100.114.228.138:50731 MAIL_SEND(BROADCAST_DISTRIBUTED)->{[3]@100.114.228.138@{50746,50747}|[1],[3]@100.114.228.138@{50731,50732}|[0]}
        │                           └── [4]@100.114.228.138:50731 PROJECT
        │                               └── [4]@100.114.228.138:50731 FILTER
        │                                   └── [4]@100.114.228.138:50731 TABLE SCAN (userGroups) null
        └── [1]@100.114.228.138:50731 MAIL_RECEIVE(HASH_DISTRIBUTED)
            ├── [5]@100.114.228.138:50746 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]}
            │   └── [5]@100.114.228.138:50746 PROJECT
            │       └── [5]@100.114.228.138:50746 FILTER
            │           └── [5]@100.114.228.138:50746 TABLE SCAN (userGroups) null
            └── [5]@100.114.228.138:50731 MAIL_SEND(HASH_DISTRIBUTED)->{[1]@100.114.228.138@{50752,50753}|[3],[1]@100.114.228.138@{50746,50747}|[2],[1]@100.114.228.138@{50737,50738}|[1],[1]@100.114.228.138@{50731,50732}|[0]}
                └── [5]@100.114.228.138:50731 PROJECT
                    └── [5]@100.114.228.138:50731 FILTER
                        └── [5]@100.114.228.138:50731 TABLE SCAN (userGroups) null
```
logical plan
```
Execution Plan
LogicalJoin(condition=[=($3, $5)], joinType=[semi])
  PinotLogicalExchange(distribution=[hash[3]])      <-- THIS should be the right exchange
    PinotLogicalExchange(distribution=[hash[3]])      <-- THIS exchange is redundant
      LogicalJoin(condition=[=($3, $5)], joinType=[semi])
        LogicalProject(daysSinceFirstTrip=[$3], deviceOS=[$4], totalTrips=[$5], userUUID=[$6])
          LogicalFilter(condition=[<($5, 100)])
            LogicalTableScan(table=[[userAttributes]])
        PinotLogicalExchange(distribution=[broadcast], relExchangeType=[PIPELINE_BREAKER])
          LogicalProject(groupUUID=[$3], userUUID=[$4])
            LogicalFilter(condition=[AND(<>($3, 'group-3'), <>($3, 'group-4'))])
              LogicalTableScan(table=[[userGroups]])
  PinotLogicalExchange(distribution=[hash[1]])
    LogicalProject(groupUUID=[$3], userUUID=[$4])
      LogicalFilter(condition=[AND(<>($3, 'group-3'), <>($3, 'group-4'))])
        LogicalTableScan(table=[[userGroups]])
```

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #11880

### CODE REVIEW

**Review by xiangfu0 — APPROVED** [review]

File: pinot-query-planner/src/main/java/org/apache/pinot/query/planner/logical/PlanFragmenter.java [hunk 1]
```diff
@@ -128,6 +128,8 @@ public PlanNode visitExchange(ExchangeNode node, Context context) {
     }
     int currentPlanFragmentId = context._previousPlanFragmentId;
     int nextPlanFragmentId = ++context._currentPlanFragmentId;
+    // Set previous PlanFragment ID in the context to be the next PlanFragment ID to be used by the child node.
+    context._previousPlanFragmentId = nextPlanFragmentId;
```
Comment (walterddr) [inline pinot-query-planner/src/main/java/org/apache/pinot/query/planner/logical/PlanFragmenter.java:132]: the logic of previous/current plan fragment id looks very convoluted

in normal node, _previousPlanFragmentId is set to the "node itself before it visit its children, thus guaranteed at the time child is being visit, current is always what the child is suppose to be on, and the previous is what the parent suppose to be on. 

in exchange `_previousPlanFragmentId` setting to the next plan fragment id seems weird. 

the actual problem is once exchange visits the child, the plan break into fragment's and thus --> it should be named "parent plan fragment id" and b/c mailbox send doesn't have a parent it is defined as a the "virtual node" sits on top of the MailboxSend and granted the same id as the current node 

^which still seems weird, i wonder keeping this as a global context might not be the best way

Comment (walterddr) [reply pinot-query-planner/src/main/java/org/apache/pinot/query/planner/logical/PlanFragmenter.java:132]: this might be more clear: 
```suggestion
    // for exchange node: visiting the next node effectively breaks the plan into 2 parts and thus there's no definition
    // of _previousPlanFragmentId for the next planFragmentRoot: thus setting both Ids to the nextPlanFragmentId as a start
    context._currentPlanFragmentId = context._previousPlanFragmentId = nextPlanFragmentId;```
