### PR TITLE
fix spammy logs for ConfluentSchemaRegistryRealtimeClusterIntegrationTest [MINOR]

### LINKED ISSUE #9240: ConfluentSchemaRegistry IntegrationTest prints huge logs
https://github.com/apache/pinot/runs/7890686433?check_suite_focus=true
```
2022-08-18T02:12:33.6547446Z [INFO] Running org.apache.pinot.integration.tests.KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest
...
2022-08-18T02:14:26.6174836Z 02:14:25.310 ERROR [KafkaConfluentSchemaRegistryAvroMessageDecoder] [mytable__0__0__20220818T0214Z] Caught exception while decoding row in topic KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest, discarding row
2022-08-18T02:14:26.6175975Z org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
2022-08-18T02:14:26.6176584Z Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
2022-08-18T02:14:26.6177510Z 02:14:25.867 ERROR [KafkaConfluentSchemaRegistryAvroMessageDecoder] [mytable__1__0__20220818T0214Z] Caught exception while decoding row in topic KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest, discarding row
2022-08-18T02:14:26.6178539Z org.apache.kafka.common.errors.SerializationException: Error deserializing Avro message for id -1
2022-08-18T02:14:26.6179139Z Caused by: org.apache.kafka.common.errors.SerializationException: Unknown magic byte!
...
```
going on for 120,000 lines.

### PR DESCRIPTION
**Pull request by agavra**
fixes #9240 

to test the desired functionality there's no need to insert as many invalid records as valid ones, this PR changes the functionality to just insert a few for each avro file

I tested this locally and this reduces the number of `"Unknown magic byte!"` logs to 120 and re-enables logging for this test.

cc @npawar

### CODE REVIEW

File: pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest.java [hunk 1]
```diff
@@ -129,29 +130,39 @@ protected void pushAvroIntoKafka(List<File> avroFiles)
...
       try (DataFileStream<GenericRecord> reader = AvroUtils.getAvroReader(avroFile)) {
         for (GenericRecord genericRecord : reader) {
           byte[] keyBytes = (getPartitionColumn() == null) ? Longs.toByteArray(System.currentTimeMillis())
               : (genericRecord.get(getPartitionColumn())).toString().getBytes();
-          // Ignore getKafkaMessageHeader()
-          nonAvroProducer.send(new ProducerRecord<>(getKafkaTopic(), keyBytes, "Rubbish".getBytes(UTF_8)));
+
+          if (numInvalidRecords < NUM_INVALID_RECORDS) {
+            // send a few rubbish records to validate that the consumer will skip over non-avro records, but
+            // don't spam them every time as it causes log spam
```
Comment (walterddr) [inline pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest.java:161]: do we still need to change the test behavior since you already suppressed them in the log4j2.xml config?

Comment (agavra) [reply pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest.java:161]: I think we should - this will allow us to re-enable the logs (helpful for debugging in the future) and the test should run faster since it's producing way less garbage to kafka

Comment (walterddr) [reply pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest.java:161]: i wasn't sure if the original intent for this test is to produce large amount of garbage into kafka. :-P that's why I was wondering if we shouldn't change the behavior of the test

Comment (walterddr) [reply pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/KafkaConfluentSchemaRegistryAvroMessageDecoderRealtimeClusterIntegrationTest.java:161]: looks good to merge. checked in the original PR
