### PR TITLE
Fix to query inconsistencies under heavy upsert load (resolves #7958)

### LINKED ISSUE #7958: Intermittent query inconsistencies under heavy upsert with single segment
After testing upsert loads with latest master (including https://github.com/apache/pinot/pull/7844), we still see occasional inconsistent queries (i.e. receiving intermittently fewer records than previously known), even with using only a single (large enough) segment.

The test table has 1 million position records. After an initial load of all 1 million records, we continuously push upsert into Kafka running ingestion at essentially full capacity. Simultaneously we issue `select count(*) from position` every second to test whether we get expected results of 1 million. 

After apply 7844 merge, results mostly return 1 million as expected but with occasional outliers of 999,999, 999,998 etc. The frequency of which seems to depend on machine specs.

Potentially, the few inconsistencies could be related to order of snapshots in FilterPlanNode - taking a snapshot of the total number of documents _before_ taking the snapshot of validity bitmap. We are experimenting with switching that around (https://github.com/tuor713/pinot/commit/22c518e4df55572efbc35cb63c76eee731d44fcf) and in preliminary tests that appears to eliminate all inconsistent results (or at the very least drastically reduce their frequency).

### PR DESCRIPTION
**Pull request by tuor713**
## Description
Even with a single segment, count queries occasionally return too few results (off by one or two). Reason appears to be that in the `FilterPlanNode` the number of documents is snapshotted before the validity bitmap, which means in between documents can be upsert with the new valid documents beyond the snapshotted `_numDocs`.

This PR snapshots the bitmap first, then number of documents during the construction of the `FilterPlanNode`.

## Upgrade Notes
Does this PR prevent a zero down-time upgrade?
No

Does this PR fix a zero-downtime upgrade introduced earlier?
No

Does this PR otherwise need attention when creating release notes?
No

## Testing
- One unit test added to expose the snapshot inconsistency of `FilterNodePlan`.
- Tested manually in constructed example case (1 controller, 1 broker, 1 server, 1 RT table)
   - 500k unique records initially inserted
   - After that ingest 5mm updates after initial population is loaded, all on existing keys (segment size is 10mm so no segment roll)
   - During ingestion continuously query `select count(*) from <table>`, which is expected to stay constant at 500k
   - After this fix any inconsistencies of counts less than 500k disappear.
- The same held true in a larger real-life installation (4 servers, 10mm unique records): outside of segment roll queries consistently return the correct count of unique records

### CODE REVIEW

File: pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java [hunk 1]
```diff
@@ -73,20 +84,19 @@ public FilterPlanNode(IndexSegment indexSegment, QueryContext queryContext) {
...
     FilterContext filter = _queryContext.getFilter();
-    ThreadSafeMutableRoaringBitmap validDocIds = _indexSegment.getValidDocIds();
-    boolean applyValidDocIds = validDocIds != null && !QueryOptionsUtils.isSkipUpsert(_queryContext.getQueryOptions());
+    boolean applyValidDocIds = _validDocIds != null && !QueryOptionsUtils.isSkipUpsert(_queryContext.getQueryOptions());
     if (filter != null) {
       BaseFilterOperator filterOperator = constructPhysicalOperator(filter);
       if (applyValidDocIds) {
         BaseFilterOperator validDocFilter =
-            new BitmapBasedFilterOperator(validDocIds.getMutableRoaringBitmap(), false, _numDocs);
+                new BitmapBasedFilterOperator(_validDocIds, false, _numDocs);
```
Comment (snleee) [inline pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:92]: Are you using the pinot code style?
https://docs.pinot.apache.org/developers/developers-and-contributors/code-setup#setup-ide

**Review by snleee — COMMENTED** [review]
Are we trying to capture some rows that get appended `after numDocs gets snapshotted and before validDocId gets snapshotted`? If we fire another query, I think that those new rows should show up. If that's the case, I'm not sure if we have the inconsistency issue.

File: pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java (hunk 1 above)
Comment (tuor713) [reply pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:92]: Ah my bad let me fix that.

Comment (tuor713) [reply pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:92]: With regard to first question: what I am trying to fix is known ids disappearing temporarily from the results. Say there are 1000 positions with ids 1-1000 and they are all published at the start of the day and then updated during the day. Whenever I query regardless of what upsets are in place I would like to get exactly 1000 items back - one for each id.

What is currently happening is that numDocs is snapshotted - say 50,000 during the middle of the day - then concurrently some id, is updated and the new update is in row 50,001 and the bitmap is updated - lastly the validDocId bitmap is snapshotted. That means when the query runs row 50,001 is excluded due to the numDoc snapshot and the result is only 999 docs - one missing.

This kind of case - missing one or two records that were previously available - happens fairly reliable and is the result of snapshotting the total docs first while concurrent operations can still happen on the validity bitmap.

**Comment by tuor713** [comment]
Formatting fixed for both files.

File: pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java [hunk 2]
```diff
@@ -52,19 +52,30 @@
...
+  private final MutableRoaringBitmap _validDocIds;
 
   // Cache the predicate evaluators
   private final Map<Predicate, PredicateEvaluator> _predicateEvaluatorMap = new HashMap<>();
 
   public FilterPlanNode(IndexSegment indexSegment, QueryContext queryContext) {
     _indexSegment = indexSegment;
     _queryContext = queryContext;
+
+    // Snapshot validDocIds *before* _numDocs since otherwise newest upserts could get lost
```
Comment (Jackie-Jiang) [inline pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:71]: Taking snapshot when creating the plan nodes can potentially cause performance issue since it is done single-threaded

**Review by Jackie-Jiang — COMMENTED** [review]
Thanks for adding the test.
I didn't realize this PR and opened another one #8018. I've closed that one and let's use this PR to address the issue, but please take a look at the code in #8018 which shows the suggested change.

File: pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java (hunk 2 above)
Comment (tuor713) [reply pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:71]: Good point. From what I could see the FilterPlanNode constructor call site is currently always adjacent to the run method invocation (DocSetIdPlanNode#run, AggregationPlanNode#run, AggregationGroupByPlanNode#run, AggregationGroupByOrderByPlanNode#run) so I don't think that it could currently make a difference whether snapshotting happens in constructor or run. However, the intent of other operators seems definitely to be that run happens during parallelized execution. From that perspective the approach in #8018 to only snapshot in the run method is definitely preferable.

Only question I had was what the original reason was behind the checkpointing in the constructor (given the same argument as above it seems to make no practical difference at the moment :)?

Comment (Jackie-Jiang) [reply pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:71]: Oh you are right. We recently changed the logic of `FilterPlanNode`, and it is not constructed in the plan maker, so there is no practical difference now

Comment (richardstartin) [reply pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:71]: In any case I know how to make snapshots faster in the library given that the bitmap is only ever appended to, so we could do that work if it ever showed up in profiles.

Comment (Jackie-Jiang) [reply pinot-core/src/main/java/org/apache/pinot/core/plan/FilterPlanNode.java:71]: @richardstartin It is not only appended to, but also modified. We can probably keep the writer in the `ThreadSafeMutableRoaringBitmap` and only create the bitmap during the snapshot if that gives better performance

**Comment by tuor713** [comment]
Build failures may be transient :( What I saw in the JDK 11 Quickstart test is that the build ran successfully and the test seemed to complete but the post job cleanup failed to upload to some (Github?) cache. What's the usual approach here - try to rerun, rebase on master and retry, dig into the failures in this PR?

```
2022-01-18T19:26:57.6881659Z Post job cleanup.
2022-01-18T19:26:57.8637035Z [command]/usr/bin/tar -cz -f /home/runner/work/_temp/3051cf70-7cdf-4c5f-9732-07cffd83b882/cache.tgz -C /home/runner/.m2/repository .
2022-01-18T19:28:52.2887996Z [warning]Cache service responded with 400 during chunk upload.
2022-01-18T19:28:52.2921708Z events.js:187
2022-01-18T19:28:52.2923145Z       throw er; // Unhandled 'error' event
2022-01-18T19:28:52.2923523Z       ^
2022-01-18T19:28:52.2923727Z 
2022-01-18T19:28:52.2923978Z Error: EBADF: bad file descriptor, read
2022-01-18T19:28:52.2924355Z Emitted 'error' event on ReadStream instance at:
2022-01-18T19:28:52.2924852Z     at internal/fs/streams.js:167:12
2022-01-18T19:28:52.2925172Z     at FSReqCallback.wrapper [as oncomplete] (fs.js:470:5) {
2022-01-18T19:28:52.2925961Z   errno: -9,
2022-01-18T19:28:52.2926187Z   code: 'EBADF',
2022-01-18T19:28:52.2926532Z   syscall: 'read'
2022-01-18T19:28:52.2926727Z }
```

**Comment by richardstartin** [comment]
Hi @tuor713 I have rerun the tests, but this is something which needs to be investigated.

**Comment by tuor713** [comment]
@richardstartin Thanks a lot - the new build fails with different failures :) I will take a look to see what might be happening.

**Comment by mayankshriv** [comment]
Seems like we didn't conclude on this PR. @tuor713 may I request to rebase, resolve the conflicts and address any open questions/comments? We can then get this merged. cc: @Jackie-Jiang

**Comment by Jackie-Jiang** [comment]
Please also take a look at the approach in #8018. Even though it is practically the same, snapshotting in `run()` is cleaner IMO

**Comment by tuor713** [comment]
@Jackie-Jiang Makes sense - in terms of procedure is it ok to take the commit 8018 then add the test on top as a separate commit (so authorship stays clear) and rebase or should I do it a different way?

**Comment by Jackie-Jiang** [comment]
@tuor713 When merging, the commits will be squashed into one. Let me reopen 8018, and we can rebase this PR to add the test

**Comment by Jackie-Jiang** [comment]
@tuor713 Just merged #8392. Can you please rebase the current master to add the test?

**Comment by mayankshriv** [comment]
Seems like the prerequisite PR https://github.com/apache/pinot/pull/8392 has been merged. @tuor713 , would you like to rebase and merge this one?

**Review by Jackie-Jiang — APPROVED** [review]
