### PR TITLE
Fix the group-by reduce handling when query times out

### LINKED ISSUE #8449: Issue with broker timeout handling results in ArrayOutOfBoundsException
It seems getTopRecords called from the public method finish is invoked without a read lock. We are seeing an issue where we get ArrayIndexOutOfBoundsException when running a query that involves ConcurrentIndexedTable. See the stack trace below:

  Filing an issue after discussion with @Jackie-Jiang 

> pinot-broker-2 broker java.lang.ArrayIndexOutOfBoundsException: Index 118 out of bounds for length 118
>   pinot-broker-0 broker at org.apache.pinot.core.data.table.TableResizer.getTopRecords(TableResizer.java:225) ~[pinot-all-0.9.0-jar-with-dependencies.jar:0.9.0-281a3866b37cc4a0f527948845246a8dbb789b33]
>   pinot-broker-2 broker at org.apache.pinot.core.data.table.TableResizer.getSortedTopRecords(TableResizer.java:239) ~[pinot-all-0.9.0-jar-with-dependencies.jar:0.9.0-281a3866b37cc4a0f527948845246a8dbb789b33]
>   pinot-broker-0 broker at org.apache.pinot.core.data.table.IndexedTable.finish(IndexedTable.java:150) ~[pinot-all-0.9.0-jar-with-dependencies.jar:0.9.0-281a3866b37cc4a0f527948845246a8dbb789b33]

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #8449 

When broker times out, there are multiple places not handled properly:
- Should check the return value of `CountDownLatch.await()` to identify if the query times out
- `Future[]` length should be the reduce group size
- When the query times out, the result table won't be set, so reading rows from the result table can cause NPE

### CODE REVIEW

File: pinot-core/src/test/java/org/apache/pinot/core/query/reduce/BrokerReduceServiceTest.java [hunk 1]
```diff
@@ -0,0 +1,79 @@
...
+    DataTable dataTable = dataTableBuilder.build();
+    Map<ServerRoutingInstance, DataTable> dataTableMap = new HashMap<>();
+    int numInstances = 1000;
+    for (int i = 0; i < numInstances; i++) {
+      ServerRoutingInstance instance = new ServerRoutingInstance("localhost", i, TableType.OFFLINE);
+      dataTableMap.put(instance, dataTable);
+    }
+    long reduceTimeoutMs = 1;
+    BrokerResponseNative brokerResponse =
+        brokerReduceService.reduceOnDataTable(brokerRequest, brokerRequest, dataTableMap, reduceTimeoutMs, null);
```
Comment (ashishkf) [inline pinot-core/src/test/java/org/apache/pinot/core/query/reduce/BrokerReduceServiceTest.java:74]: brokerRequest param is duplicated.

Comment (Jackie-Jiang) [reply pinot-core/src/test/java/org/apache/pinot/core/query/reduce/BrokerReduceServiceTest.java:74]: This is intentional. The first arg is the broker side broker request, second arg is the server side broker request.
