### PR TITLE
[multistage][bugfix] fix non-grouping agg result issue

### LINKED ISSUE #10124: [multistage] Aggregation Query with No Grouping Sets Returns Empty Response
When we run an aggregation query without any grouping-sets, if no rows match the operators under the aggregation then the result is empty. Example:

```
select
  count(*)
from
  baseballStats_OFFLINE
WHERE
  playerID IN (
    select
      playerID
    from
      baseballStats_OFFLINE
    where
      teamID = 'foo'
  )
```

The expected behavior here would be to receive a single row `[0]` but instead we don't get any rows.

For the case when a stage does a full aggregate (as opposed to a partial aggregate), if there's no grouping key we may want to assign only 1 worker for that stage since otherwise it may be hard to ensure that stages above the full aggregate stage receive exactly 1 row which contains all the aggregation functions.

Opening this issue for discussing any other solutions.

cc: @walterddr @siddharthteotia

### PR DESCRIPTION
**Pull request by walterddr**
follow up on #10211
this fixes #10124

### CODE REVIEW

File: pinot-query-runtime/src/main/java/org/apache/pinot/query/runtime/operator/AggregateOperator.java [hunk 1]
```diff
@@ -353,22 +369,22 @@ private static class Accumulator {
...
       if (rexExpression instanceof RexExpression.InputRef) {
         _inputRef = ((RexExpression.InputRef) rexExpression).getIndex();
         _literal = null;
-        dataType = inputSchema.getColumnDataType(_inputRef);
+        _dataType = inputSchema.getColumnDataType(_inputRef);
       } else {
         _inputRef = -1;
         _literal = ((RexExpression.Literal) rexExpression).getValue();
-        dataType = DataSchema.ColumnDataType.fromDataType(rexExpression.getDataType(), false);
+        _dataType = DataSchema.ColumnDataType.fromDataType(rexExpression.getDataType(), true);
```
Comment (walterddr) [inline pinot-query-runtime/src/main/java/org/apache/pinot/query/runtime/operator/AggregateOperator.java:385]: this is a bug fix for a MV/SV value generator

**Review by siddharthteotia — APPROVED** [review]
