### PR TITLE
Always use segment partition id as stream partition id for single stream

### LINKED ISSUE #15952: Incorrect Stream Config Index Assignment for Partition IDs for Tables with Only 1 Stream Config
**Description**: PR #[13790](https://github.com/apache/pinot/pull/13790) introduced an assumption that partition IDs map to specific stream config indices based on their modulo 10000 value. This change caused ingestion failures during testing - we use a custom ingestion plugin that use partition IDs outside the expected range (> 10000).

**Current Behavior:**
Partition IDs are assumed to follow a pattern where:
- 0-9999 maps to index 0
- 10000-19999 maps to index 1
- and so on
- This assumption is applied even when there is only one stream config

**Problem**: At Stripe, we use a custom ingestion plugin with partition IDs such as 65000 and 128000. These IDs are generated using a combination where:

The first half of the bytes represent a Kafka cluster
The latter half represent a Kafka partition ID
With the current implementation, a partition ID of 65000 incorrectly maps to index 5, despite having only one stream config in our table configuration.

**Desired Behaviour:**
- When there is only one stream config, the modulo 10000 calculation should not be used to determine the stream config index.
- The partition ID to stream config index mapping should be more flexible to accommodate custom ingestion plugins and partition ID schemes

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #15952 

Specialize single steam case to always use segment partition id as stream partition id

### CODE REVIEW

**Comment by Jackie-Jiang** [comment]
@lnbest0707-uber Can you help take a look?

cc @priyen-stripe

File: pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/realtime/PinotLLCRealtimeSegmentManager.java [hunk 1]
```diff
@@ -276,20 +276,47 @@ public List<PartitionGroupConsumptionStatus> getPartitionGroupConsumptionStatusL
...
-          getSegmentZKMetadata(streamConfigs.get(0).getTableNameWithType(), llcSegmentName.getSegmentName());
-      PartitionGroupConsumptionStatus partitionGroupConsumptionStatus =
-          new PartitionGroupConsumptionStatus(partitionGroupId, llcSegmentName.getSequenceNumber(),
-              offsetFactory.create(segmentZKMetadata.getStartOffset()),
-              segmentZKMetadata.getEndOffset() == null ? null : offsetFactory.create(segmentZKMetadata.getEndOffset()),
-              segmentZKMetadata.getStatus().toString());
-      partitionGroupConsumptionStatusList.add(partitionGroupConsumptionStatus);
+    String tableNameWithType = streamConfigs.get(0).getTableNameWithType();
+    int numStreams = streamConfigs.size();
+    if (numStreams == 1) {
```
Comment (lnbest0707-uber) [inline pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/realtime/PinotLLCRealtimeSegmentManager.java:281]: Looks like the multi-streams section logic is fully compatible with this single stream. We could potentially merge it?

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeSegmentDataManager.java [hunk 2]
```diff
@@ -1620,9 +1620,20 @@ public RealtimeSegmentDataManager(SegmentZKMetadata segmentZKMetadata, TableConf
     // TODO Validate configs
     IndexingConfig indexingConfig = _tableConfig.getIndexingConfig();
     _partitionGroupId = llcSegmentName.getPartitionGroupId();
-    _streamPatitionGroupId = IngestionConfigUtils.getStreamPartitionIdFromPinotPartitionId(_partitionGroupId);
-    _streamConfig = new StreamConfig(_tableNameWithType, IngestionConfigUtils.getStreamConfigMaps(_tableConfig)
-        .get(IngestionConfigUtils.getStreamConfigIndexFromPinotPartitionId(_partitionGroupId)));
+    List<Map<String, String>> streamConfigMaps = IngestionConfigUtils.getStreamConfigMaps(_tableConfig);
+    int numStreams = streamConfigMaps.size();
+    if (numStreams == 1) {
+      // Single stream
```
Comment (lnbest0707-uber) [inline pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeSegmentDataManager.java:1626]: Same here, why do we extract the `numStreams == 1` case

File: pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/realtime/PinotLLCRealtimeSegmentManager.java (hunk 1 above)
Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/realtime/PinotLLCRealtimeSegmentManager.java:281]: For single stream case, we don't want to do the partition id to stream partition id conversion. This is to handle the scenario where user's custom stream uses partition id higher than 10000. See the issue linked in the PR. Adding some comments explaining this.
Also, single stream is the much more common case, so specializing it with simplified logic is good for performance

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeSegmentDataManager.java (hunk 2 above)
Comment (Jackie-Jiang) [reply pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeSegmentDataManager.java:1644]: Same here. We want to skip the step of partition id translation

File: pinot-spi/src/main/java/org/apache/pinot/spi/stream/PartitionGroupConsumptionStatus.java [hunk 3]
```diff
@@ -18,49 +18,51 @@
...
+  public PartitionGroupConsumptionStatus(int partitionGroupId, int sequenceNumber, StreamPartitionMsgOffset startOffset,
+      StreamPartitionMsgOffset endOffset, String status) {
+    this(partitionGroupId, partitionGroupId, sequenceNumber, startOffset, endOffset, status);
+  }
+
   public int getPartitionGroupId() {
     return _partitionGroupId;
   }
 
   public int getStreamPartitionGroupId() {
```
Comment (KKcorps) [inline pinot-spi/src/main/java/org/apache/pinot/spi/stream/PartitionGroupConsumptionStatus.java:64]: nit: we should rename the method to `getStreamPartitionId` as well we are changing the variable name

Comment (Jackie-Jiang) [reply pinot-spi/src/main/java/org/apache/pinot/spi/stream/PartitionGroupConsumptionStatus.java:64]: I thought about that, but this is an SPI change, so didn't do that
