### PR TITLE
Fix JSONPath cache inefficient issue

### LINKED ISSUE #7403: JSONPath cache is inefficient
In a profile collected from a user, we see over 20% of CPU time in JSONPath's `LRUCache` 
Capture

This is caused by contention caused by locking:
CaptureLock

The cache exists to prevent from compiling JSONPaths repeatedly, and uses an LRU mechanism to avoid high memory consumption in unknown use cases where there could be an unbounded number of JSON paths. In Pinot, the number of JSON paths is bounded by the size of the transformation config, so this caching mechanism is inappropriate.

It is possible to override the cache implementation by calling `com.jayway.jsonpath.spi.cache.CacheProvider.setCache(new MyCache());`. The user implemented `Cache` backed by a `ConcurrentHashMap` and reported that the issue was resolved - so this should be investigated and the user would like to contribute the implementation which they are now using in production.

### PR DESCRIPTION
**Pull request by Ferrari6**
## Description
this commit fixes #7403 

**stack trace**
image

 _**flamegraphs can be found in the issue descriptions #7403 **_

### Fix
A new JSON path cache is implemented using ConcurrentHashMap, and the cache threshold is set at the same time. When the maximum is exceeded, the JSON path will not be cached anymore.

- In Pinot, the number of JSON paths is bounded by the size of the transformation config
- Even if it exceeds the maximum cache size, not cache JSON path may be better than frequent swapping in and out of LRU
- If JSON path compile is not cached, CPU consumption is also very small

### 

```
"transformConfigs": [
        {
          "columnName": "id",
          "transformFunction": "jsonPathString(report,'$.identifiers.id','')"
        },
       {
          "columnName": "name",
          "transformFunction": "jsonPathString(report,'$.identifiers.name','')"
        },
 ...
]
```

### Pinot Server Flamegraphs when using ConcurrentHashMap cache (28vcpu)

image
image
**jsonpath CPU usage is low and no lock contentions**
-->
## Upgrade Notes
Does this PR prevent a zero down-time upgrade? (Assume upgrade order: Controller, Broker, Server, Minion)
* [ ] Yes (Please label as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR fix a zero-downtime upgrade introduced earlier?
* [ ] Yes (Please label this as **<code>backward-incompat</code>**, and complete the section below on Release Notes)

Does this PR otherwise need attention when creating release notes? Things to consider:
- New configuration options
- Deprecation of configurations
- Signature changes to public methods/interfaces
- New plugins added or old plugins removed
* [ ] Yes (Please label this PR as **<code>release-notes</code>** and complete the section on Release Notes)

### CODE REVIEW

File: pinot-common/src/test/java/org/apache/pinot/common/function/JsonPathMapCacheTest.java [hunk 1]
```diff
@@ -0,0 +1,65 @@
...
+    String path = "$.contact.email";
+    assertEquals(JsonFunctions.jsonPathString(_jsonString, path), "test@example.com");
+    JsonPathMapCache cache = (JsonPathMapCache) CacheProvider.getCache();
+
+    // verify json path has been cached
+    LinkedList<Predicate> filterStack = new LinkedList<>(Collections.emptyList());
+    String cacheKey = Utils.concat(path, filterStack.toString());
+    JsonPath jsonPath = cache.get(cacheKey);
+    assertNotNull(jsonPath);
+  }
```
Comment (richardstartin) [inline pinot-common/src/test/java/org/apache/pinot/common/function/JsonPathMapCacheTest.java:64]: This depends on undocumented library behaviour, it assumes the format of the cache keys. I have actually submitted a PR to the library to change this behaviour, which would break this test: https://github.com/json-path/JsonPath/pull/750

I suggest iterating over the map instead (requires exposing the keys on `JsonPathMapCache`).

Comment (richardstartin) [reply pinot-common/src/test/java/org/apache/pinot/common/function/JsonPathMapCacheTest.java:64]: Or just use a Mockito spy and verify `put` was called, I guess.

Comment (Ferrari6) [reply pinot-common/src/test/java/org/apache/pinot/common/function/JsonPathMapCacheTest.java]: Good suggestions. 
I always prefer to use Mockitio for unit testing, but all method calls related to JSONFunctions are static, so I try to check the map size now.

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java [hunk 2]
```diff
@@ -0,0 +1,66 @@
...
+  public JsonPath get(String key) {
+    return _pathCache.get(key);
+  }
+
+  /**
+   * cache JsonPath, if reached size limit, not cache it anymore.
+   */
+  @Override
+  public void put(String key, JsonPath value) {
+    if (this.size() < _limit) {
```
Comment (richardstartin) [inline pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:54]: This is obviously racy and doesn't provide a hard bound, but I don't think it matters.

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java [hunk 3]
```diff
@@ -0,0 +1,66 @@
...
+ * This cache for avoiding repeatedly compiling JSON path string when using jsonPathXXX transformations
+ *
+ * <p>The existing jay way LRUCache is very inefficient, It will cause
+ * a lot of unnecessary lock waits during high concurrent data ingestion,
+ * and LRU mechanism is inappropriate for Pinot bounded size of the
+ * transformation config, so we should use this simple Map cache instead
+ * of it.
+ */
+public class JsonPathMapCache implements Cache {
+  private final ConcurrentMap<String, JsonPath> _pathCache = new ConcurrentHashMap<>(128, 0.75f, 1);
```
Comment (richardstartin) [inline pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:36]: I don't think we need to explicitly set the concurrency level or load factor, these are the default values any way.

File: pinot-common/src/main/java/org/apache/pinot/common/function/FunctionConstants.java [hunk 4]
```diff
@@ -0,0 +1,31 @@
...
+public class FunctionConstants {
+  private FunctionConstants() {
+  }
+
+  /**
+   * Maximum of json path cache size.
+   * the number of JSON paths is bounded by the size of the transformation config,
+   * add this threshold for protection from the extreme cases.
+   */
+  public static final int MAX_JSON_PATH_CACHE_SIZE = 1024 * 16;
```
Comment (richardstartin) [inline pinot-common/src/main/java/org/apache/pinot/common/function/FunctionConstants.java:30]: This class should be removed and the constant inlined into `JsonPathMapCache` where it is relevant.

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java (hunk 2 above)
Comment (Ferrari6) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:54]: Yes, it doesn't need a hard bound.

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java (hunk 3 above)
Comment (Ferrari6) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:36]: I will change it.  This is the habit of my previous team!

**Review by richardstartin — APPROVED** [review]
Not an approver but this looks good to me, and solves a big problem 👍🏻

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java [hunk 5]
```diff
@@ -0,0 +1,61 @@
...
+import java.util.concurrent.ConcurrentMap;
+
+/**
+ * This cache for avoiding repeatedly compiling JSON path string when using jsonPathXXX transformations
+ *
+ * <p>The existing jay way LRUCache is very inefficient, It will cause
+ * a lot of unnecessary lock waits during high concurrent data ingestion,
+ * and LRU mechanism is inappropriate for Pinot bounded size of the
+ * transformation config, so we should use this simple Map cache instead
+ * of it.
```
Comment (Jackie-Jiang) [inline pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: JsonPath can also be used at query time (see `JsonExtractScalarTransformFunction`). Let's add a TODO here to add some evict policy in the future

**Review by Jackie-Jiang — APPROVED** [review]
LGTM otherwise

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java (hunk 5 above)
Comment (richardstartin) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: I think in the future this can be handled better by just precompiling `JsonPath` objects and bypassing the library's cache entirely. For transformConfig, it would require changes to the way `ScalarFunction` is defined as well as changes to `InbuiltFunctionEvaluator.planExecution`. For `JsonExtractScalarTransformFunction` the change is trivial. 

I think in the meantime using a guava `Cache` instead of a `ConcurrentHashMap` as suggested on slack would alleviate this concern.

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java [hunk 6]
```diff
@@ -0,0 +1,61 @@
...
+    return _pathCache.get(key);
+  }
+
+  /**
+   * cache JsonPath, if reached size limit, not cache it anymore.
+   */
+  @Override
+  public void put(String key, JsonPath value) {
+    if (this.size() < _limit) {
+      // use putIfAbsent to handle concurrency put
```
[the remark this answers is not in the document]
Comment (Ferrari6) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:50]: Both are safe of these two puts, but there will be duplicated put when a cache misses because there is no mutex lock from get to put. I think putIfAbsent can reduce one unnecessary Map node value assignment. I think it may doesn't matter.

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java (hunk 5 above)
Comment (Ferrari6) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: I think guava `Cache` is a more safe cache solution cause the `JsonPath` cache will also be applied to the query.
For one of my table ingestion cases, reading data QPS close to 10w and configuring `JsonPath` transformations with dozens of fields, this will put a certain pressure on GC and CPU because of the LRU algorithm needs to record every `get`. Of course, this should not become a system bottleneck, but the implementation is a bit too heavy.

Comment (Ferrari6) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: Guava Cache uses `recencyQueue` to record cache accesses. A large number of `CAS` enqueue operations generated by hotkeys will cause CPU consumption, and this synchronous recording will also slow down cache reading.

I think maybe [Caffeine Cache](https://github.com/ben-manes/caffeine) is a good choice. Its Striped-RingBuffer design is more efficient for GC and CPU usage. And its API is very similar to Guava Cache.

Comment (richardstartin) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: Whether using Guava's cache would result in high CPU consumption needs measurement. I agree that Caffeine is a better cache implementation, but Guava is already on the classpath. Is this particular use case important enough to add a 1MB depedency?

**Comment by snleee** [comment]
@Ferrari6 Can you rebase based on the master branch and retrigger github action tests?

**Comment by Ferrari6** [comment]
> @Ferrari6 Can you rebase based on the master branch and retrigger github action tests? We recently introduced the flakyness to one of our integration test and fixed from #7432

yes, sure. But because the setCache of CacheProvider in Jayway can only be called once, and once getCache is called, it cannot be setCache again. So I need to do some code changes.

**Comment by Ferrari6** [comment]
Both `JsonFunctions` and `JsonExtractScalarTransformFunction` use JsonPath, so need to set Jayway's `CacheProvider` before the initialization of these two functions and can only be set once. At the same time, I am also doing some performance tests on `Guava Cache`, I will submit some more code soon.

File: pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java (hunk 5 above)
Comment (ben-manes) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: You will likely be fine using Guava if you increase the concurrency level (e.g. to 64, defaults to 4). That will stripe the LRU so that there is less contention, but will still suffer at peak loads ([benchmarks](https://github.com/ben-manes/caffeine/wiki/Benchmarks#read-100-1)). For your use-case here that is likely good enough given other costs, e.g. JsonPath's [inefficiencies](https://github.com/json-path/JsonPath/issues/740). Unfortunately my patches to Guava that gave it a ~25x boost were not accepted due to a lack of a champion, and instead they simply updated the JavaDoc to recommend Caffeine. 🙂

Comment (Ferrari6) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: I think we should use the default value of the `concurrencyLevel` of `Guava cache`. In this scenario, there will be very few caches writes and no need to update the cache. My concern is the way Guava records cache reads, which is not very efficient.

Comment (ben-manes) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: The performance of cache reads improves with the concurrency level due to reducing the likelihood of contending on the same CLQ instance. The benchmarks use a zipf to simulate a hotspot.

Comment (Ferrari6) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: You are right.

Comment (richardstartin) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: Thanks for the insights @ben-manes. FWIW I have been using Caffeine in commercial projects for years, the only question here is whether _this_ particular use case is worth adding a relatively large (in bytes) dependency.

Comment (ben-manes) [reply pinot-common/src/main/java/org/apache/pinot/common/function/JsonPathMapCache.java:33]: It's not a problem. I co-authored Guava's so either way my code is used. 😄 

@Ferrari6 is correct in what your preference and default should be, though. Prior to my involvement, the Guava team bet on reference caching (MapMaker) and spent their complexity budget by forking the hash table as an optimization. This was a mistake because soft references can cause GC death spirals of stop the world events and unpredictable evictions, but looked fine in a naive benchmark. This blew their complexity budget, so porting size eviction from [CLHM](https://github.com/ben-manes/concurrentlinkedhashmap) favored simplicity over performance.

The longer-term problem you'll face is that no one maintains CacheBuilder. The last big change was adding Map.compute, but it was riddled with major bugs and done inefficiently. I fixed some of those problems, but there are show stoppers. If you keep to the historic functionality then Guava's can be made acceptable in most cases. Caffeine does have jar bloat by code generating per-configuration entry classes to minimize the memory footprint. In those cases where disk is a premium some projects embed CLHM into their code base, e.g. msjdbc and groovy. You'll probably have many caches throughout Pinot making the Caffeine dependency worthwhile even if you can get by in a case-by-case basis.

**Comment by mayankshriv** [comment]
Some tests failed, rerunning to see if intermittent issue due to timeouts.

**Comment by Ferrari6** [comment]
> Some tests failed, rerunning to see if intermittent issue due to timeouts.

Thanks @mayankshriv. I have fixed the failed tests.

**Comment by mayankshriv** [comment]
@Ferrari6 There's unit test failures (I reran a couple of times). Do you mind investigating? cc: @richardstartin

**Comment by mayankshriv** [comment]
w

> > Some tests failed, rerunning to see if intermittent issue due to timeouts.
> 
> Thanks @mayankshriv. I have fixed the failed tests.

@Ferrari6 seems like there are still failing tests.
