### PR TITLE
[multistage] don't prune project after agg during relBuilder

### LINKED ISSUE #12013: [multistage][bug] multi semi-join hint not applied in weird conditions
#11937 introduces multi-join capability however there are several scenarios that this didn't apply
```
select /+ joinOptions(join_strategy = 'dynamic_broadcast') /
--[work]      key, COUNT(*)
--[work]      *
--[work]      sum(val)
--[work]      sum(1)
--[not work]  count(val)
--[not work]  count(*)
from tbl
where col1 IN (select col from  dim1 where  ...)
    and col2 IN (select col from dim2 where ...)
    and col3 IN (select col from dim3 where ...)
group by key
```

specificallly when COUNT(*) is being used without agg-group, multi-semi join rules doesn't apply and 2 of the 3 IN clause are still modeled as shuffled inner-join

### PR DESCRIPTION
**Pull request by walterddr**
we already have agg-project merge rule. no need to do it during relbuilder. which might cause eliminating project useful for other rules.

this fix #12013

### CODE REVIEW

File: pinot-query-planner/src/main/java/org/apache/pinot/query/QueryEnvironment.java [hunk 1]
```diff
@@ -122,7 +122,8 @@ public QueryEnvironment(TypeFactory typeFactory, CalciteSchema rootSchema, Worke
             // SUB-QUERY Threshold is useless as we are encoding all IN clause in-line anyway
             .withInSubQueryThreshold(Integer.MAX_VALUE)
             .addRelBuilderConfigTransform(c -> c.withPushJoinCondition(true))
-            .addRelBuilderConfigTransform(c -> c.withAggregateUnique(true)))
+            .addRelBuilderConfigTransform(c -> c.withAggregateUnique(true))
+            .addRelBuilderConfigTransform(c -> c.withPruneInputOfAggregate(false)))
```
Comment (Jackie-Jiang) [inline pinot-query-planner/src/main/java/org/apache/pinot/query/QueryEnvironment.java:126]: (minor) Can we chain them as `.addRelBuilderConfigTransform(c -> c.withPushJoinCondition(true).withAggregateUnique(true).withPruneInputOfAggregate(false))`?

**Review by Jackie-Jiang — APPROVED** [review]

File: pinot-query-planner/src/main/java/org/apache/pinot/query/QueryEnvironment.java (hunk 1 above)
Comment (walterddr) [reply pinot-query-planner/src/main/java/org/apache/pinot/query/QueryEnvironment.java:126]: good point. just saw this, will clean up later
