### PR TITLE
fix multiple instances where the number of placeholders did not match the number of arguments to logging methods

### LINKED ISSUE #12132: fix instances where the number of {} placeholders in the logger message doesn't match the number of other arguments to the logging call
found a number of instances where the number of `{}` placeholders in the logger message doesn't match the number of other arguments to the logging call. 

for example...

```
_segmentLogger.error("Illegal state {}" + _state.toString());
```
should be...
```
_segmentLogger.error("Illegal state {}", _state.toString());
```

### PR DESCRIPTION
**Pull request by timveil**
This PR fixes #12132.  Found a number of instances where the number of logging placeholders did not match the number of arguments to the logging method.  This would result in unexpected and possibly unhelpful logging messages.

### CODE REVIEW

File: pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/SegmentDeletionManager.java [hunk 1]
```diff
@@ -154,7 +154,7 @@ protected synchronized void deleteSegmentFromPropertyStoreAndLocal(String tableN
         }
       }
     } catch (Exception e) {
-      LOGGER.warn("Caught exception while checking helix states for table {} " + tableName, e);
+      LOGGER.warn(String.format("Caught exception while checking helix states for table [%s]", tableName), e);
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/SegmentDeletionManager.java:157]:
```suggestion
      LOGGER.warn("Caught exception while checking helix states for table: {}", tableName, e);
```

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeSegmentDataManager.java [hunk 2]
```diff
@@ -379,7 +379,7 @@ private boolean endCriteriaReached() {
         }
         return false;
       default:
-        _segmentLogger.error("Illegal state {}" + _state.toString());
+        _segmentLogger.error("Illegal state [{}]", _state.toString());
```
Comment (Jackie-Jiang) [inline pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/RealtimeSegmentDataManager.java:382]:
```suggestion
        _segmentLogger.error("Illegal state: {}", _state);
```

File: pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/SegmentBuildTimeLeaseExtender.java [hunk 3]
```diff
@@ -102,7 +102,7 @@ public void shutDown() {
       Future future = entry.getValue();
       boolean cancelled = future.cancel(true);
       if (!cancelled) {
-        LOGGER.warn("Task could not be cancelled for {}" + entry.getKey());
+        LOGGER.warn("Task could not be cancelled for [{}]", entry.getKey());
```
Comment (Jackie-Jiang) [inline pinot-core/src/main/java/org/apache/pinot/core/data/manager/realtime/SegmentBuildTimeLeaseExtender.java:105]:
```suggestion
        LOGGER.warn("Task could not be cancelled for {}", entry.getKey());
```

**Review by Jackie-Jiang — APPROVED** [review]
Good catch! We usually use `:` to separate argument, so suggest keeping the same convention

**Review by walterddr — APPROVED** [review]
