### PR TITLE
Fix the time segment pruner on TIMESTAMP data type

### LINKED ISSUE #12721: TimeSegmentPruner exception based on query and schema datetime column format
We have the following datetime column in our schema
```
date_time_field_specs:
- name: created
   data_type: TIMESTAMP
   format: 1:MILLISECONDS:EPOCH
   granularity: 1:HOURS
```
The pinot [schema docs](https://docs.pinot.apache.org/configuration-reference/schema) are vary confusing and vague, but this is seemingly an allowed way to configure the column.

When we try to query the table with the time pruner enabled and a `where created between '2024-03-22 16:18:51.000' and '2024-03-22 21:37:41.000'` clause, the broker fails with the following stacktrace.
```
java.lang.NumberFormatException: Character array is missing "e" notation exponential mark.
	at java.math.BigDecimal.<init>(BigDecimal.java:581) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:405) ~[?:?]
	at java.math.BigDecimal.<init>(BigDecimal.java:838) ~[?:?]
	at org.apache.pinot.spi.data.DateTimeFormatSpec.fromFormatToMillis(DateTimeFormatSpec.java:305) 
 	at org.apache.pinot.broker.routing.segmentpruner.TimeSegmentPruner.getFilterTimeIntervals(TimeSegmentPruner.java:281) 
 	at org.apache.pinot.broker.routing.segmentpruner.TimeSegmentPruner.getFilterTimeIntervals(TimeSegmentPruner.java:178) 
 	at org.apache.pinot.broker.routing.segmentpruner.TimeSegmentPruner.prune(TimeSegmentPruner.java:138) 
 	at org.apache.pinot.broker.routing.BrokerRoutingManager$RoutingEntry.calculateRouting(BrokerRoutingManager.java:788) 
 	at org.apache.pinot.broker.routing.BrokerRoutingManager.getRoutingTable(BrokerRoutingManager.java:612) 
 	at org.apache.pinot.broker.requesthandler.BaseBrokerRequestHandler.handleRequest(BaseBrokerRequestHandler.java:593) 
 	at org.apache.pinot.broker.requesthandler.BaseBrokerRequestHandler.handleRequest(BaseBrokerRequestHandler.java:263) 
 	at org.apache.pinot.broker.requesthandler.BrokerRequestHandlerDelegate.handleRequest(BrokerRequestHandlerDelegate.java:107) 
 	at org.apache.pinot.broker.api.resources.PinotClientRequest.executeSqlQuery(PinotClientRequest.java:317) 
 	at org.apache.pinot.broker.api.resources.PinotClientRequest.executeSqlQuery(PinotClientRequest.java:294) 
 	at org.apache.pinot.broker.api.resources.PinotClientRequest.processSqlQueryPost(PinotClientRequest.java:157) 
```

It seems related to the fact that `EPOCH` is parsed [one way](https://github.com/apache/pinot/blob/0a08a919ea6122212a1b2963de1f40cee84f6742/pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFormatSpec.java#L276-L277) and [timestamp](https://github.com/apache/pinot/blob/0a08a919ea6122212a1b2963de1f40cee84f6742/pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFormatSpec.java#L278-L279) a totally different way.

Changing the format to `1:MILLISECONDS:TIMESTAMP` allows the query to succeed.

Overall there's several issues here

- [ ] Failing timestamp parsing in the `TimeSegmentPruner` can fail the whole query. This should not be allowed for something that's supposed to be an optimization
- [ ] `1:MILLISECONDS:TIMESTAMP` is specifically allowed in code, but it's not documented anywhere. Should it be used? Is it valid? Is it what we want here?
- [x] `1:MILLISECONDS:EPOCH` cannot parse `yyyy-mm-dd hh:mm:ss[.fffffffff]` correctly
- [ ] I'm fairly certain `5:HOURS:TIMESTAMP` would be a valid format, but it just always ignore the `5`

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #12721 

When data type is TIMESTAMP, fix the format to be "TIMESTAMP" because the time format is already implicit from the data type.

### CODE REVIEW

File: pinot-broker/src/main/java/org/apache/pinot/broker/routing/segmentpruner/TimeSegmentPruner.java [hunk 1]
```diff
@@ -18,6 +18,7 @@
  */
 package org.apache.pinot.broker.routing.segmentpruner;
 
+import com.google.common.base.Preconditions;
```
Comment (jadami10) [inline pinot-broker/src/main/java/org/apache/pinot/broker/routing/segmentpruner/TimeSegmentPruner.java:21]: this whole file is a refactor. you're getting the format from the `DateTimeFieldSpec` rather then unnecessarily passing it. but nothing is actually changing here.

File: pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFieldSpec.java [hunk 2]
```diff
@@ -74,6 +75,10 @@ public DateTimeFieldSpec(String name, DataType dataType, String format, String g
       @Nullable Object sampleValue) {
     super(name, dataType, true);
 
+    // Override format to be "TIMESTAMP" for TIMESTAMP data type because the format is implicit
+    if (dataType == DataType.TIMESTAMP) {
```
Comment (jadami10) [inline pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFieldSpec.java:79]: will this change people's schemas as they're stored in ZK, or just modify them every time they're loaded in ZK?

I almost wonder if we should go the route of not letting create/update happen with this rather than silently changing it so folks are aware

**Review by jadami10 — APPROVED** [review]
one question, but this looks great

File: pinot-broker/src/main/java/org/apache/pinot/broker/routing/segmentpruner/TimeSegmentPruner.java (hunk 1 above)
Comment (Jackie-Jiang) [reply pinot-broker/src/main/java/org/apache/pinot/broker/routing/segmentpruner/TimeSegmentPruner.java:21]: Correct. I started with making changes in this file, but then in the end find I can simply override the `format`

File: pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFieldSpec.java (hunk 2 above)
Comment (Jackie-Jiang) [reply pinot-spi/src/main/java/org/apache/pinot/spi/data/DateTimeFieldSpec.java:79]: This won't change existing schema. New uploaded/modified schema will be changed.
This reminds me that I do need to change the JSON setter so that create/update can be changed

**Review by xiangfu0 — APPROVED** [review]
