### PR TITLE
Case order bug

### LINKED ISSUE #8747: Case statement doesn't result in short circuiting
Currently CASE statements don't follow SQL conventions to short circuit at the first match. In the documentation, we have a given example:
```
SELECT
    CASE
      WHEN price > 30 THEN 3
      WHEN price > 20 THEN 2
      WHEN price > 10 THEN 1
      ELSE 0
    END AS price_category
FROM myTable
```
This results in the last met WHEN condition taking precedence instead of the first. In the example above, all values with `price > 10` will evaluate to 1. 

Curious if this is intentional for any reason as the code below explicitly takes the max condition index. Otherwise, happy to make this change.

https://github.com/apache/pinot/blob/5cd6a7dc05135a82f8dc292efcce682c8d377338/pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/CaseTransformFunction.java#L226-L232

### PR DESCRIPTION
**Pull request by richardstartin**
A bug was introduced in #8138 which eliminated the evaluation of never taken then statements, however, it also reversed the case order of precedence. This fixes this regression, but also adds a test to assert that correct case precedence is observed.

Fixes #8747

### CODE REVIEW

File: pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/CaseTransformFunction.java [hunk 1]
```diff
@@ -256,13 +253,9 @@ public int[] transformToIntValuesSV(ProjectionBlock projectionBlock) {
       if (_selections[i]) {
         TransformFunction transformFunction = _elseThenStatements.get(i);
         int[] intValues = transformFunction.transformToIntValuesSV(projectionBlock);
-        if (_numSelections == 1) {
```
Comment (richardstartin) [inline pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/CaseTransformFunction.java:259]: this optimisation is removed because it can only trigger if only the else statement matches, which is unlikely in the typical case.

File: pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/CaseTransformFunction.java [hunk 2]
```diff
@@ -86,13 +87,13 @@ public void init(List<TransformFunction> arguments, Map<String, DataSource> data
...
     }
-    // Add ELSE Statement first
     _elseThenStatements = new ArrayList<>(numWhenStatements + 1);
-    _elseThenStatements.add(arguments.get(numWhenStatements * 2));
-    for (int i = numWhenStatements; i < numWhenStatements * 2; i++) {
+    for (int i = numWhenStatements; i < numWhenStatements * 2 + 1; i++) {
       _elseThenStatements.add(arguments.get(i));
     }
     _selections = new boolean[_elseThenStatements.size()];
+    Collections.reverse(_elseThenStatements);
```
Comment (cliandy) [inline pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/CaseTransformFunction.java:95]: Can we add a comment here to indicate the reasoning?

**Review by walterddr — APPROVED** [review]

File: pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/CaseTransformFunction.java (hunk 2 above)
[the remark this answers is not in the document]
Comment (richardstartin) [reply pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/CaseTransformFunction.java:95]: Good suggestion, I'll follow up with cosmetic enhancements but want to get this merged quickly given the nature of the bug
