### PR TITLE
Fix TableDoesNotExistError for hybrid tables in MSE queries in controller API

### LINKED ISSUE #16032: TableDoesNotExistError for MSE queries on hybrid tables
I'm running a simple `select * from my_table limit 10`.

- this works with the v1 engine
- this works with both engines if I do my_table_REALTIME
- this works with both engines if I do my_table_OFFLINE

This fails for `my_table` on the v2 engine
```
Error Code: 190 (TableDoesNotExistError)

TableDoesNotExistError: Unable to find table in cluster, table does not exist for tables: [<my_table>]
```

### PR DESCRIPTION
**Pull request by vrajat**
#15773 added support for logical tables in controller query API. However the support broke queries that referenced hybrid tables.

This PR fixes bug by simplifying the loop. Previously there were two sets of two loops - one to find tables and another to find logical tables. Two loops made it hard to find out if tables were found or not.

In the fix, only a single loop on table names is used to check for both physical and logical tables. 

Another issue was that there were no tests to check changes in this part of the code. A couple of tests have been added to test controller query API.

Closes #16032

### CODE REVIEW

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 1]
```diff
@@ -332,38 +308,43 @@ private StreamingOutput getQueryResponse(String query, @Nullable SqlNode sqlNode
...
-      List<TableConfig> tableConfigList = new ArrayList<>();
       if (_pinotHelixResourceManager.hasRealtimeTable(actualTableName)) {
-        tableConfigList.add(Objects.requireNonNull(_pinotHelixResourceManager.getRealtimeTableConfig(actualTableName)));
+        brokerTenants.add(Objects.requireNonNull(_pinotHelixResourceManager.getRealtimeTableConfig(actualTableName)).getTenantConfig()
+            .getBroker());
+        found = true;
       }
       if (_pinotHelixResourceManager.hasOfflineTable(actualTableName)) {
-        tableConfigList.add(Objects.requireNonNull(_pinotHelixResourceManager.getOfflineTableConfig(actualTableName)));
+        brokerTenants.add(Objects.requireNonNull(_pinotHelixResourceManager.getOfflineTableConfig(actualTableName)).getTenantConfig().getBroker());
```
Comment (yashmayya) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java]: Checkstyle violations on line length here

Comment (vrajat) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java]: Fixed
