### PR TITLE
Use fixed thread pool in Pinot Controller

### LINKED ISSUE #13990: Pinot Controller leader re-election not triggered
We faced an issue in production wherein the controller leader node went down but re-election was not triggered. This lead to segment upload errors for tables trying to commit a segment, instances being marked as unavailable for the segment and finally queries failing for the tables with segments unavailable error. 
Pinot version - 1.0.x

Timeline for this was as follows:
1. A GET call for a large table's segments' metadata `tables/<tablename>/segments/<segmentName>/metadata?columns=*` spawns ~75k threads. This cause a huge memory spike and heap to go out of memory (heap size being 128GB here), maybe crashing the node. We suspect it was because of reload status button which triggers the segment metadata call
Screenshot 2024-09-12 at 7 11 38 PM

2. The node's 2 zk sessions time out at 17:19:56, the node tries to reestablish connection but it keeps emitting metrics as a leader until 17:29:x
Screenshot 2024-09-12 at 7 11 05 PM

3. The health check for node starts failing around 17:20:x, but standby controller nodes keep polling and getting failed leader's session ID as leader until 18:10 when we triggered a force replacement of error node
Screenshot 2024-09-12 at 7 19 24 PM

```
Instance 123 is not leader of cluster production-cluster due to current session 702147796290178 does not match leader session 702147796290171
```

Ideally the re-election should've triggered around 17:20.

### PR DESCRIPTION
**Pull request by cypherean**
Replaces `CachedThreadPool` with `FixedThreadPool` in Pinot Controller. 

We've observed the max thread count in prod controller over a 7 day period to be ~500 which is set as the default thread pool size. The thread pool size is kept configurable.
image (7)

Fixes #13990

### CODE REVIEW

File: pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java [hunk 1]
```diff
@@ -278,6 +278,7 @@ private static long getRandomInitialDelayInSeconds() {
   private static final String SERVER_ADMIN_REQUEST_TIMEOUT_SECONDS = "server.request.timeoutSeconds";
   private static final String MINION_ADMIN_REQUEST_TIMEOUT_SECONDS = "minion.request.timeoutSeconds";
   private static final String SEGMENT_COMMIT_TIMEOUT_SECONDS = "controller.realtime.segment.commit.timeoutSeconds";
+  private static final String CONTROLLER_NUM_THREAD_POOL = "controller.numThreadPool";
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java:281]: `numThreadPool` is a little bit misleading, how about `controller.executor.numThreads`

File: pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java [hunk 2]
```diff
@@ -321,6 +322,7 @@ private static long getRandomInitialDelayInSeconds() {
       AutoRebalanceStrategy.class.getName();
   private static final int DEFAULT_LEAD_CONTROLLER_RESOURCE_REBALANCE_DELAY_MS = 300_000; // 5 minutes
   private static final String DEFAULT_DIM_TABLE_MAX_SIZE = "200M";
+  private static final int DEFAULT_CONTROLLER_NUM_THREAD_POOL = 500;
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java:325]: This magic number might not always work. Suggest falling back to cached pool when it is not configured

File: pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java [hunk 3]
```diff
@@ -252,10 +253,13 @@ public void init(PinotConfiguration pinotConfiguration)
       // ControllerStarter::start()}
       _helixResourceManager = createHelixResourceManager();
       // This executor service is used to do async tasks from multiget util or table rebalancing.
+      _numThreadPool = _config.getControllerNumThreadPool();
       _executorService =
-          Executors.newCachedThreadPool(new ThreadFactoryBuilder().setNameFormat("async-task-thread-%d").build());
+          Executors.newFixedThreadPool(_numThreadPool, new ThreadFactoryBuilder()
+                  .setNameFormat("async-task-thread-%d").build());
       _tenantRebalanceExecutorService =
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java:260]: Not introduced in this PR, but having 2 thread pool is hard to manage. I think we can just remove the `_tenantRebalanceExecutorService` and always use `_executorService`. @shounakmk219 wdyt?

**Comment by itschrispeck** [comment]
I was wondering if this fully solves the linked issue, could task accumulation from improper/out of date fixed pool size lead to a similar OOM scenario?

A more involved approach might be to manage a TPE ourselves, similar to [ScalingThreadPoolExecutor](https://github.com/apache/pinot/blob/c4e03e369789251f62436cefdc30445e6435429c/pinot-common/src/main/java/org/apache/pinot/common/utils/ScalingThreadPoolExecutor.java#L45) but with a task submission timeout/rejection policy.

File: pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java (hunk 3 above)
Comment (shounakmk219) [reply pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java:260]: We can. 
The tenant rebalance job is a long running activity which allows parallelism and now that we have a fixed pool we don't want to block critical operations by occupying threads from the shared pool for such long durations. 
Maybe we should cap the degree of parallelism on tenant rebalance to certain % of `numThreadPool`?

**Comment by cypherean** [comment]
> I was wondering if this fully solves the linked issue, could task accumulation from improper/out of date fixed pool size lead to a similar OOM scenario?
> 
> A more involved approach might be to manage a TPE ourselves, similar to [ScalingThreadPoolExecutor](https://github.com/apache/pinot/blob/c4e03e369789251f62436cefdc30445e6435429c/pinot-common/src/main/java/org/apache/pinot/common/utils/ScalingThreadPoolExecutor.java#L45) but with a task submission timeout/rejection policy.

@Jackie-Jiang @shounakmk219 are you aligned with the ScalingThreadPool? I can make the changes then.

File: pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java (hunk 3 above)
Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java:260]: Good point! Should we make it a different configurable then? Basically keeping 2 thread pools, but allow them to be configured separately?
To a second thought, should be consider moving all rebalance tasks to a different thread pool? Rebalance is in general long running tasks which doesn't require much CPU

Comment (shounakmk219) [reply pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java:260]: Makes sense

File: pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java [hunk 4]
```diff
@@ -266,6 +266,16 @@ public void init(PinotConfiguration pinotConfiguration)
     TableConfigUtils.setEnforcePoolBasedAssignment(_config.isEnforcePoolBasedAssignmentEnabled());
   }
 
+  // If thread pool size is not configured executor will use cached thread pool
+  private ExecutorService createExecutorService(int numThreadPool, String threadNameFormat) {
+    ThreadFactory threadFactory = new ThreadFactoryBuilder()
+            .setNameFormat(threadNameFormat)
+            .build();
+    return (numThreadPool == 0)
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java:274]: For robustness
```suggestion
    return (numThreadPool <= 0)
```

File: pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java [hunk 5]
```diff
@@ -266,6 +266,16 @@ public void init(PinotConfiguration pinotConfiguration)
     TableConfigUtils.setEnforcePoolBasedAssignment(_config.isEnforcePoolBasedAssignmentEnabled());
   }
 
+  // If thread pool size is not configured executor will use cached thread pool
+  private ExecutorService createExecutorService(int numThreadPool, String threadNameFormat) {
+    ThreadFactory threadFactory = new ThreadFactoryBuilder()
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/BaseControllerStarter.java:271]: (format) Re-format with Pinot Style

File: pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java [hunk 6]
```diff
@@ -69,6 +69,8 @@ public class ControllerConf extends PinotConfiguration {
   public static final String CONTROLLER_MODE = "controller.mode";
   public static final String LEAD_CONTROLLER_RESOURCE_REBALANCE_STRATEGY = "controller.resource.rebalance.strategy";
   public static final String LEAD_CONTROLLER_RESOURCE_REBALANCE_DELAY_MS = "controller.resource.rebalance.delay_ms";
+  private static final String LEAD_CONTROLLER_RESOURCE_REBALANCE_NUM_THREADS =
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java:72]: Let's keep them `public` in case we want to use these constants to set config

Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java:72]: This config is not for lead controller resource (lead controller resource is a Helix resource to manage lead controller). Let's rename it to `controller.executor.rebalance.numThreads`

File: pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java [hunk 7]
```diff
@@ -408,6 +412,10 @@ public void setRealtimeSegmentCommitTimeoutSeconds(int timeoutSec) {
     setProperty(SEGMENT_COMMIT_TIMEOUT_SECONDS, Integer.toString(timeoutSec));
   }
 
+  public void setControllerNumThreadPool(int numThreadPool) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java:415]: Make the method name align with config, e.g. `setControllerExecutorNumThreads()`, same for other places

File: pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java [hunk 8]
```diff
@@ -321,6 +324,7 @@ private static long getRandomInitialDelayInSeconds() {
       AutoRebalanceStrategy.class.getName();
   private static final int DEFAULT_LEAD_CONTROLLER_RESOURCE_REBALANCE_DELAY_MS = 300_000; // 5 minutes
   private static final String DEFAULT_DIM_TABLE_MAX_SIZE = "200M";
+  private static final int EMPTY_THREAD_POOL = 0;
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/ControllerConf.java:327]: Suggest using `-1` to represent unspecified. Default to empty thread pool can be a little bit confusing

**Review by tibrewalpratik17 — APPROVED** [review]
The change lgtm!

**Comment by tibrewalpratik17** [comment]
@Jackie-Jiang does this change address all your comments? Waiting for your approval before merging this.

**Comment by Jackie-Jiang** [comment]
Thanks for the contribution! Please help update pinot doc about these new configs
