### PR TITLE
[multistage] support multi-tenant lookup for v2 engine

### LINKED ISSUE #11237: [multistage] support common broker tenant
#10336 supported tenant-based v2 queries. 

however it doesn't handle cross-tenant access when tables are residing in different tenant but the broker has knowledge over all tables
the following table config will fail in controller query endpoint (but will success in broker query endpoint) b/c controller cannot find the common broker with the overlapping tenant configuration.
- table config
```
tableA: ...
    "tenants": {
      "broker": "TA",
      "server": "TA"
    },
tableB: ...
    "tenants": {
      "broker": "TB",
      "server": "TB"
    },
```
- instance conf
```
BROKER: ...
    "TAG_LIST": [
      "DefaultTenant_BROKER",
      "TA_BROKER",
      "TB_BROKER"
    ]
SERVER0: ...
    "TAG_LIST": [
      "TA_OFFLINE",
      "TA_REALTIME"
    ]
SERVER1: ...
    "TAG_LIST": [
      "TB_OFFLINE",
      "TB_REALTIME"
    ]
```
- query:
```
SELECT COUNT(*) FROM tableA JOIN tableB USING (key)
```

### PR DESCRIPTION
**Pull request by walterddr**
this fixes #11237

### CODE REVIEW

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 1]
```diff
@@ -299,16 +277,40 @@ private List<TableConfig> getListTableConfigs(List<String> tableNames) {
...
+      if (commonInstances == null) {
+        commonInstances = instances;
+      } else {
+        commonInstances.retainAll(instances);
+      }
+    }
+    return commonInstances == null ? Collections.emptyList() : new ArrayList<>(commonInstances);
+  }
+
   // return the brokerTenant if all table configs point to the same broker, else returns null
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:307]: Please update the javadoc

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 2]
```diff
@@ -299,16 +277,40 @@ private List<TableConfig> getListTableConfigs(List<String> tableNames) {
...
-  private String getCommonBrokerTenant(List<TableConfig> tableConfigList) {
-    Set<String> tableBrokers = new HashSet<>();
+  private Set<String> getCommonBrokerTenants(List<TableConfig> tableConfigList) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:308]: This is no longer the common broker tenants, but all broker tenants

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 3]
```diff
@@ -214,31 +215,19 @@ private String getMultiStageQueryResponse(String query, String queryOptions, Htt
...
+      if (brokerTenants.isEmpty()) {
         return QueryException.getException(QueryException.BROKER_REQUEST_SEND_ERROR, new Exception(
             String.format("Unable to dispatch multistage query with multiple tables : %s " + "on different tenant",
                 tableNames))).toString();
       }
     } else {
       // TODO fail these queries going forward. Added this logic to take care of tautologies like BETWEEN 0 and -1.
-      List<String> allBrokerList = new ArrayList<>(_pinotHelixResourceManager.getAllBrokerTenantNames());
-      brokerTenant = allBrokerList.get(RANDOM.nextInt(allBrokerList.size()));
+      brokerTenants = _pinotHelixResourceManager.getAllBrokerTenantNames();
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:226]: This doesn't seem correct. We should pick a random tenant

Comment (Jackie-Jiang) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:226]: Actually, directly picking a random broker might be even better

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java (hunk 2 above)
Comment (walterddr) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:308]: will rename

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 4]
```diff
@@ -214,31 +215,19 @@ private String getMultiStageQueryResponse(String query, String queryOptions, Htt
...
-
-    instanceIds.retainAll(_pinotHelixResourceManager.getOnlineInstanceList());
-    if (instanceIds.isEmpty()) {
-      return QueryException.BROKER_INSTANCE_MISSING_ERROR.toString();
-    }
-
-    // Send query to a random broker.
-    String instanceId = instanceIds.get(RANDOM.nextInt(instanceIds.size()));
+    List<String> instanceIds = findCommonBrokerInstance(brokerTenants);
+    String instanceId = selectInstanceId(instanceIds);
```
Comment (tibrewalpratik17) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:230]: So previous behaviour was that we selected one broker at random and sent query there. Now we are trying to find a common instance among all the brokers. This will result in not sending the query at all right? Correct me if I am getting this wrong. 

What i understand from this change is say there are 3 brokers: broker1, broker2, broker3. broker1 and broker2 has one instance in common and broker3 has no intersection. Then we should send the query to the intersection of broker1 and broker2. But here we will fail the query as all 3 of them have no intersection.

Comment (walterddr) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:230]: no. i think that's the problem with previous implementation. what i did here is:
1. get a UNION of all the table's broker tag from all the tables (not intersect). e.g. tableA has tenant tag A and tableB has tenant tag B then the UNION will be [A, B]
2. get a list of brokers that contains all the broker tags in the UNION --> only the broker that are tagged with both A and B will be selected. 
3. select a random broker from the list of brokers.

Comment (tibrewalpratik17) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:230]: Umm yes but say in a scenario where there are 3 tables  -- tableA, tableB, tableC on broker tenants A, B, C.
Interesection of [A, B] has 2 broker-instances common but brokertenant C as no instances common to either A or B. In this case, `findCommonBrokerInstance` will return Collections.emptyList() and `selectInstanceId` will return BROKER_RESOURCE_MISSING_ERROR.

Here `_pinotHelixResourceManager.getAllBrokerTenantNames()` doesn't include tableNames that are passed in the query but all tables in the cluster. Chances are high that there are no common instances among all these table brokerTenants.

Comment (walterddr) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:230]: well if your query access table A B and C at the same time it should do just that. b/c there's no way to run a query to join A B and C together without a broker knowing the info of all 3 tables

Comment (tibrewalpratik17) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:230]: But what if my query access only table A and B here even then it would fail right?

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java (hunk 3 above)
Comment (walterddr) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:226]: what would be the best solution here? i don't see a get random broker instance API in helix resource manager. should i add one?

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java (hunk 4 above)
Comment (walterddr) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java]: no it won't. the brokerTenant (brokerTenantUnion in new code) will only contain the unioned tag from table A and B.

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 5]
```diff
@@ -202,43 +203,28 @@ private String getMultiStageQueryResponse(String query, String queryOptions, Htt
...
       }
 
-      // When routing a query, there should be at least one common broker tenant for the table. However, the server
-      // tenants can be completely disjoint. The leaf stages which access segments will be processed on the respective
-      // server tenants for each table. The intermediate stages can be processed in either or all of the server tenants
-      // belonging to the tables.
-      brokerTenant = getCommonBrokerTenant(tableConfigList);
-      if (brokerTenant == null) {
+      // find the unions of all the broker tenant tags of the queried tables.
+      Set<String> brokerTenantsUnion = getBrokerTenantTagsUnion(tableConfigList);
```
Comment (walterddr) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:215]: this extracts the union of all tags used by the tables from the query only @tibrewalpratik17

File: pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/PinotHelixResourceManager.java [hunk 6]
```diff
@@ -469,6 +469,11 @@ public List<InstanceConfig> getBrokerInstancesConfigsFor(String tableName) {
         TagNameUtils.getBrokerTagForTenant(brokerTenantName));
   }
 
+  public List<InstanceConfig> getAllBrokerInstanceConfigs() {
+    return HelixHelper.getInstanceConfigs(_helixZkManager).stream()
+        .filter(instance -> InstanceTypeUtils.isBroker(instance.getId())).collect(Collectors.toList());
+  }
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/helix/core/PinotHelixResourceManager.java:475]: We can add API to get all broker instance ids which is much cheaper
```suggestion
  public List<String> getAllBrokerInstances() {
    return HelixHelper.getAllInstances(_helixAdmin, _clusterName).stream()
        .filter(instanceId -> InstanceTypeUtils.isBroker(instanceId)).collect(Collectors.toList());
  }
```

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 7]
```diff
@@ -299,16 +274,40 @@ private List<TableConfig> getListTableConfigs(List<String> tableNames) {
...
+      return QueryException.BROKER_INSTANCE_MISSING_ERROR.toString();
     }
-    if (tableBrokers.size() != 1) {
-      return null;
+
+    // Send query to a random broker.
+    return instanceIds.get(RANDOM.nextInt(instanceIds.size()));
+  }
+
+  private List<String> findCommonBrokerInstance(Set<String> brokerTenants) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:291]:
```suggestion
  private List<String> findCommonBrokerInstances(Set<String> brokerTenants) {
```

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 8]
```diff
@@ -299,16 +274,40 @@ private List<TableConfig> getListTableConfigs(List<String> tableNames) {
...
+    Set<String> commonInstances = null;
+    for (String brokerTenant : brokerTenants) {
+      Set<String> instances = _pinotHelixResourceManager.getAllInstancesForBrokerTenant(brokerTenant);
+      if (commonInstances == null) {
+        commonInstances = instances;
+      } else {
+        commonInstances.retainAll(instances);
+      }
+    }
+    return commonInstances == null ? Collections.emptyList() : new ArrayList<>(commonInstances);
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:301]: `commonInstances` can never be `null` here because `brokerTenants` is not empty

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 9]
```diff
@@ -299,16 +274,40 @@ private List<TableConfig> getListTableConfigs(List<String> tableNames) {
...
-      return null;
+
+    // Send query to a random broker.
+    return instanceIds.get(RANDOM.nextInt(instanceIds.size()));
+  }
+
+  private List<String> findCommonBrokerInstance(Set<String> brokerTenants) {
+    Set<String> commonInstances = null;
+    for (String brokerTenant : brokerTenants) {
+      Set<String> instances = _pinotHelixResourceManager.getAllInstancesForBrokerTenant(brokerTenant);
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:294]: It will be much faster if we first get all instance configs, and then pass in the instance configs when getting instance ids. See the `TODO` in `PinotHelixResourceManager.getAllInstancesForBrokerTenant()`

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java [hunk 10]
```diff
@@ -299,16 +274,40 @@ private List<TableConfig> getListTableConfigs(List<String> tableNames) {
...
+        commonInstances = instances;
+      } else {
+        commonInstances.retainAll(instances);
+      }
+    }
+    return commonInstances == null ? Collections.emptyList() : new ArrayList<>(commonInstances);
+  }
+
+  // return the union of brokerTenants from the tables list.
+  private Set<String> getBrokerTenantTagsUnion(List<TableConfig> tableConfigList) {
```
Comment (Jackie-Jiang) [inline pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:305]:
```suggestion
  private Set<String> getBrokerTenantsUnion(List<TableConfig> tableConfigList) {
```

**Review by Jackie-Jiang — APPROVED** [review]
LGTM otherwise

File: pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java (hunk 5 above)
Comment (tibrewalpratik17) [reply pinot-controller/src/main/java/org/apache/pinot/controller/api/resources/PinotQueryResource.java:215]: Sounds good!

**Review by tibrewalpratik17 — APPROVED** [review]
