### PR TITLE
Fix the misuse of star-tree when all predicates are always false under OR

### LINKED ISSUE #11718: [Flaky-test] StarTreeClusterIntegrationTest.testGeneratedQueries
```
Error:  Failures: 
Error:    StarTreeClusterIntegrationTest.testGeneratedQueries:163->testStarQuery:185 Query comparison failed for: 
Star Query: SELECT avg(ArrDel15) FROM mytable WHERE DivArrDelay IN (94) AND DepTimeBlk BETWEEN '1500-1559' AND '2100-2159' AND OriginCityName >= 'Bloomington/Normal, IL' AND DepTimeBlk NOT IN ('1700-1759', '2200-2259', '0001-0559') AND LongestAddGTime NOT IN (1, 58, 26, 102) AND LongestAddGTime BETWEEN 90 AND 193 AND DivArrDelay NOT IN (380, 640) AND DivArrDelay NOT IN (495, 273, 396, 1124, 280) AND LongestAddGTime <> 52
Star Response: {"resultTable":{"dataSchema":{"columnNames":["EXPR$0"],"columnDataTypes":["DOUBLE"]},"rows":[[-9999.0]]},"requestId":"324953360000000132","stageStats":{"1":{"numBlocks":1,"numRows":1,"stageExecutionTimeMs":13,"stageExecutionUnit":1,"stageExecWallTimeMs":14},"2":{"numBlocks":6,"numRows":4,"stageExecutionTimeMs":10,"stageExecutionUnit":4,"stageExecWallTimeMs":8,"tableNames":["mytable"]}},"exceptions":[],"numServersQueried":0,"numServersResponded":0,"numSegmentsQueried":12,"numSegmentsProcessed":12,"numSegmentsMatched":1,"numConsumingSegmentsQueried":0,"numConsumingSegmentsProcessed":0,"numConsumingSegmentsMatched":0,"numDocsScanned":2,"numEntriesScannedInFilter":44143,"numEntriesScannedPostFilter":4,"numGroupsLimitReached":false,"totalDocs":115545,"timeUsedMs":30,"offlineThreadCpuTimeNs":0,"realtimeThreadCpuTimeNs":0,"offlineSystemActivitiesCpuTimeNs":0,"realtimeSystemActivitiesCpuTimeNs":0,"offlineResponseSerializationCpuTimeNs":0,"realtimeResponseSerializationCpuTimeNs":0,"offlineTotalCpuTimeNs":0,"realtimeTotalCpuTimeNs":0,"segmentStatistics":[],"traceInfo":{},"numRowsResultSet":1,"minConsumingFreshnessTimeMs":0,"numSegmentsPrunedByBroker":0,"numSegmentsPrunedByServer":0,"numSegmentsPrunedInvalid":0,"numSegmentsPrunedByLimit":0,"numSegmentsPrunedByValue":0,"explainPlanNumEmptyFilterSegments":0,"explainPlanNumMatchAllFilterSegments":0,"brokerId":"Broker_10.1.0.68_18099","brokerReduceTimeMs":0}
Reference Query: SET useStarTree = false; SELECT avg(ArrDel15) FROM mytable WHERE DivArrDelay IN (94) AND DepTimeBlk BETWEEN '1500-1559' AND '2100-2159' AND OriginCityName >= 'Bloomington/Normal, IL' AND DepTimeBlk NOT IN ('1700-1759', '2200-2259', '0001-0559') AND LongestAddGTime NOT IN (1, 58, 26, 102) AND LongestAddGTime BETWEEN 90 AND 193 AND DivArrDelay NOT IN (380, 640) AND DivArrDelay NOT IN (495, 273, 396, 1124, 280) AND LongestAddGTime <> 52
Reference Response: {"resultTable":{"dataSchema":{"columnNames":["EXPR$0"],"columnDataTypes":["DOUBLE"]},"rows":[[null]]},"requestId":"324953360000000133","stageStats":{"1":{"numBlocks":1,"numRows":1,"stageExecutionTimeMs":14,"stageExecutionUnit":1,"stageExecWallTimeMs":14},"2":{"numBlocks":6,"numRows":4,"stageExecutionTimeMs":6,"stageExecutionUnit":4,"stageExecWallTimeMs":10,"tableNames":["mytable"]}},"exceptions":[],"numServersQueried":0,"numServersResponded":0,"numSegmentsQueried":12,"numSegmentsProcessed":12,"numSegmentsMatched":0,"numConsumingSegmentsQueried":0,"numConsumingSegmentsProcessed":0,"numConsumingSegmentsMatched":0,"numDocsScanned":0,"numEntriesScannedInFilter":149027,"numEntriesScannedPostFilter":0,"numGroupsLimitReached":false,"totalDocs":115545,"timeUsedMs":27,"offlineThreadCpuTimeNs":0,"realtimeThreadCpuTimeNs":0,"offlineSystemActivitiesCpuTimeNs":0,"realtimeSystemActivitiesCpuTimeNs":0,"offlineResponseSerializationCpuTimeNs":0,"realtimeResponseSerializationCpuTimeNs":0,"offlineTotalCpuTimeNs":0,"realtimeTotalCpuTimeNs":0,"segmentStatistics":[],"traceInfo":{},"numRowsResultSet":1,"minConsumingFreshnessTimeMs":0,"numSegmentsPrunedByBroker":0,"numSegmentsPrunedByServer":0,"numSegmentsPrunedInvalid":0,"numSegmentsPrunedByLimit":0,"numSegmentsPrunedByValue":0,"explainPlanNumEmptyFilterSegments":0,"explainPlanNumMatchAllFilterSegments":0,"brokerId":"Broker_10.1.0.68_18099","brokerReduceTimeMs":3}
Random Seed: 1695994992544: Iterators differ at element [1]: [[null]] != [[-9999.0]] expected [[[null]]] but found [[[-9999.0]]]
```

When null handling is enabled, star-tree should not be used

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #11718 

Fixes 2 scenarios where star-tree shouldn't be used:
- When the filter is empty (no matching doc). There is a bug when all predicates under OR are always false, it is mis-identified as always true
- When null handling is enabled for GROUP BY queries

### CODE REVIEW

File: pinot-core/src/main/java/org/apache/pinot/core/plan/GroupByPlanNode.java [hunk 1]
```diff
@@ -78,7 +78,8 @@ private GroupByOperator buildNonFilteredGroupByPlan() {
 
     // Use star-tree to solve the query if possible
     List<StarTreeV2> starTrees = _indexSegment.getStarTrees();
-    if (starTrees != null && !_queryContext.isSkipStarTree()) {
+    if (!_queryContext.isNullHandlingEnabled() && !filterOperator.isResultEmpty() && starTrees != null
```
Comment (walterddr) [inline pinot-core/src/main/java/org/apache/pinot/core/plan/GroupByPlanNode.java:81]: so we were missing null handling enable flag before as well here? :-P

**Review by walterddr — APPROVED** [review]

File: pinot-core/src/main/java/org/apache/pinot/core/plan/GroupByPlanNode.java (hunk 1 above)
Comment (Jackie-Jiang) [reply pinot-core/src/main/java/org/apache/pinot/core/plan/GroupByPlanNode.java:81]: Unfortunately yes..
