### PR TITLE
[Flaky test] fix PurgeMinionClusterIntegrationTest

### LINKED ISSUE #9581: [Flaky test] PurgeMinionClusterIntegrationTest.testPassedDelayTimePurge()
Example run: https://github.com/apache/pinot/actions/runs/3237762954/jobs/5306284570
```
Error:  Failures: 
Error:    PurgeMinionClusterIntegrationTest.testPassedDelayTimePurge:269 Expected results to contain: "rows":[[87488]] but found: {"resultTable":{"dataSchema":{"columnNames":["count(*)"],"columnDataTypes":["LONG"]},"rows":[[97109]]},"exceptions":[],"numServersQueried":1,"numServersResponded":1,"numSegmentsQueried":12,"numSegmentsProcessed":10,"numSegmentsMatched":10,"numConsumingSegmentsQueried":0,"numConsumingSegmentsProcessed":0,"numConsumingSegmentsMatched":0,"numDocsScanned":97109,"numEntriesScannedInFilter":0,"numEntriesScannedPostFilter":0,"numGroupsLimitReached":false,"totalDocs":97109,"timeUsedMs":28,"offlineThreadCpuTimeNs":358500,"realtimeThreadCpuTimeNs":0,"offlineSystemActivitiesCpuTimeNs":19265787,"realtimeSystemActivitiesCpuTimeNs":0,"offlineResponseSerializationCpuTimeNs":11700,"realtimeResponseSerializationCpuTimeNs":0,"offlineTotalCpuTimeNs":19635987,"realtimeTotalCpuTimeNs":0,"segmentStatistics":[],"traceInfo":{},"minConsumingFreshnessTimeMs":0,"numRowsResultSet":1,"numSegmentsPrunedByBroker":0,"numSegmentsPrunedByServer":2,"numSegmentsPrunedInvalid":0,"numSegmentsPrunedByLimit":0,"numSegmentsPrunedByValue":0,"explainPlanNumEmptyFilterSegments":0,"explainPlanNumMatchAllFilterSegments":0} expected [true] but found [false]
```

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #9581 
Test is flaky because server might not load the purged segments immediately. Need to wait for the condition to meet.

### CODE REVIEW

File: pinot-integration-test-base/src/test/java/org/apache/pinot/integration/tests/BaseClusterIntegrationTest.java [hunk 1]
```diff
@@ -586,11 +586,13 @@ protected void stopKafka() {
...
    */
-  protected long getCurrentCountStarResult()
-      throws Exception {
-    return getPinotConnection().execute("SELECT COUNT(*) FROM " + getTableName()).getResultSet(0).getLong(0);
+  protected long getCurrentCountStarResult() {
+    return getCountStarResult(getTableName());
+  }
+
+  protected long getCountStarResult(String tableName) {
+    return getPinotConnection().execute("SELECT COUNT(*) FROM " + tableName).getResultSet(0).getLong(0);
```
Comment (walterddr) [inline pinot-integration-test-base/src/test/java/org/apache/pinot/integration/tests/BaseClusterIntegrationTest.java:595]: why this change?

**Review by walterddr — APPROVED** [review]
lgtm.

File: pinot-integration-test-base/src/test/java/org/apache/pinot/integration/tests/BaseClusterIntegrationTest.java (hunk 1 above)
Comment (Jackie-Jiang) [reply pinot-integration-test-base/src/test/java/org/apache/pinot/integration/tests/BaseClusterIntegrationTest.java:595]: Currently yes, but this can be a commonly used method, so added it to the base class for sharing.
