### PR TITLE
Fix filtered aggregate with ordering

### LINKED ISSUE #13749: Inconsistent query results with count(*) and 1 or more "FILTER" expressions
We have a query on a realtime table with filter expressions and count(*) giving inconsistent query results. In all cases we order in descending order by count.

## [Fails] Case 1: Multiple filter expressions with some filters evaluating to 0 rows, and count(*) outside filter
```
select
  col_abc,
  count(*) as count,
  count(*) FILTER (
    WHERE
      col_type = ‘typeA’
  ) as typeA_count,
  count(*) FILTER (
    WHERE
      col_type = ‘typeB’
  ) as typeB_count,
  count(*) FILTER (
    WHERE
      col_type = ‘typeC’
  ) as typeC_count
from
  table_t
where
  created > 1718841600000.0
  and created < 1719532800000.0
  and col_abc != ''
group by
  1
order by
  count desc
limit
  15
  ```

With this query we get inconsistent responses when we run this query multiple times.

Response 1:  As you can tell the responses are also not sorted. 
```
| col_abc   | count | typeA_count | typeB_count | typeC_count |
|:----------|------:|------------:|------------:|------------:|
| January   |     2 |           2 |           0 |           0 |
| February  |     1 |           1 |           0 |           0 |
| March     |     3 |           3 |           0 |           0 |
```
Response 2: Results are sorted (and appear to be correct)
```
| col_abc   |  count | typeA_count | typeB_count | typeC_count |
|:----------|-------:|------------:|------------:|------------:|
| January   | 108440 |      108440 |           0 |           0 |
| February  |  12044 |       12044 |           0 |           0 |
| March     |   3234 |        3234 |           0 |           0 |
```

## [Passes] Case 2: Multiple FILTER expressions and count(*) also as FILTER expr 

Modifying the query to treat count(*) also as a FILTER expr appears to fix the issue and we get consistent, sorted responses even after running the query multiple times.

```
select
  col_abc,
  count(*) FILTER(WHERE true) as count,
   count(*) FILTER (
    WHERE
      col_type = ‘typeA’
  ) as typeA_count,
  count(*) FILTER (
    WHERE
      col_type = ‘typeB’
  ) as typeB_count,
  count(*) FILTER (
    WHERE
      col_type = ‘typeC’
  ) as typeC_count
from
  table_t
where
  created > 1718841600000.0
  and created < 1719532800000.0
  and col_abc != ''
group by
  1
order by
  count desc
limit
  15
```

## [Passes] Case 3: Single FILTER expression that evaluates to non-zero rows and count(*) outside filter expr 
This gives consistent responses in a sorted order by count.
```
select
  col_abc,
  count(*) as count,
  count(*) FILTER (
    WHERE
      col_type = ‘typeA’
  ) as typeA_count 
from
  table_t
where
  created > 1718841600000.0
  and created < 1719532800000.0
  and col_abc != ''
group by
  1
order by
  count desc
limit
  15
```

## [Fails] Case 4: Single FILTER expression that evaluates to zero rows and count(*) outside filter expr 
This gives inconsistent responses (similar to case 1) and not sorted by count

```
select
  col_abc,
  count(*) as count,
  count(*) FILTER (
    WHERE
      col_type = ‘typeB’
  ) as typeB_count 
from
  table_t
where
  created > 1718841600000.0
  and created < 1719532800000.0
  and col_abc != ''
group by
  1
order by
  count desc
limit
  15
```

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix #13749 

For filtered aggregate group-by queries, when there are mixed same aggregate with and without filter, and the ordering is applied to the aggregate without filter, we might get wrong result because we read the index of the aggregate from a map without filter info.
E.g. for this query: `SELECT DestCityName, COUNT(*) AS c1, COUNT(*) FILTER (WHERE AirTime = 0) AS c2 FROM mytable GROUP BY DestCityName ORDER BY c1 DESC LIMIT 10`, it might end up mistakenly ordering on `c2` column.
The fix is to remove the map of aggregate index without the filter info and always use the one with filter info.

### CODE REVIEW

File: pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineClusterIntegrationTest.java [hunk 1]
```diff
@@ -3462,6 +3454,16 @@ public void testGroupByAggregationWithLimitZero(boolean useMultiStageQueryEngine
     testQuery("SELECT Origin, SUM(ArrDelay) FROM mytable GROUP BY Origin LIMIT 0");
   }
 
+  @Test(dataProvider = "useBothQueryEngines")
+  public void testFilteredAggregationWithGroupByOrdering(boolean useMultiStageQueryEngine)
+    throws Exception {
+    setUseMultiStageQueryEngine(useMultiStageQueryEngine);
+
+    // Test the ordering is correctly applied to the correct aggregation (the one without FILTER clause)
```
Comment (gortiz) [inline pinot-integration-tests/src/test/java/org/apache/pinot/integration/tests/OfflineClusterIntegrationTest.java:3462]: nit: I would just add a mention to #13749 in this comment so readers can have more context.

We don't usually do that and it has been useful to me when reading other open source projects I know less about.

**Review by gortiz — APPROVED** [review]
