### PR TITLE
Fix Data-Correctness Bug in GTE Comparison in BinaryOperatorTransformFunction

### LINKED ISSUE #9460: Using GTE Comparison in Projection Leads to Incorrect Results
Say we have the following data:

```
some_string_col,event_timestamp,some_other_col
abc,1663795076639,5607
```

Atm this query returns 1 (which is incorrect. The first conditional expression is false):

```
SELECT
  SUM(
    CASE
      WHEN (
        (1663791467449 >= (event_timestamp - some_other_col))
        AND (1663791467449 <= event_timestamp)
      )
      THEN (1)
      ELSE 0
    END
  )
FROM
  caseWhenBug_OFFLINE
LIMIT
  100
```

If you change it to a COUNT(*), the result is accurate:

```
SELECT
  COUNT(*)
FROM
  caseWhenBug_OFFLINE
WHERE
  1663791467449 >= (event_timestamp - online_millisecs)
  AND 1663791467449 <= event_timestamp
LIMIT
  100
```

### PR DESCRIPTION
**Pull request by ankitsultana**
fixes #9460 

The [BinaryOperatorTransformFunction::compare](https://github.com/apache/pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/BinaryOperatorTransformFunction.java#L527) methods already call `getIntResult`, but the places where it's called calls `getIntResult` again. 

https://github.com/apache/pinot/blob/master/pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/BinaryOperatorTransformFunction.java#L371

Say the comparison is: 10 >= 20

Then, the call chain is (bottom-up): Double.compare(10, 20) ==> -1 ==> getIntResult(-1) ==> 0 ==> getIntResult(0) ==> 1

Which means 10 >= 20 gets evaluated to true

cc: @yupeng9 @chenboat

### CODE REVIEW

File: pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/BinaryOperatorTransformFunction.java [hunk 1]
```diff
@@ -526,17 +526,17 @@ private void fillStringResultArray(ProjectionBlock projectionBlock, BigDecimal[]
 
   private int compare(long left, double right) {
     if (Math.abs(left) <= 1L << 53) {
-      return getIntResult(Double.compare(left, right));
+      return Double.compare(left, right);
```
Comment (ankitsultana) [inline pinot-core/src/main/java/org/apache/pinot/core/operator/transform/function/BinaryOperatorTransformFunction.java:529]: Can someone share what's the best unit-test for this?

**Review by Jackie-Jiang — APPROVED** [review]
Good catch! You may add a test case in `BinaryOperatorTransformFunctionTest`

**Review by jackjlli — APPROVED** [review]
LGTM. +1 on adding a unit test for this.

**Comment by ankitsultana** [comment]
Added a UT. Existing tests weren't able to catch this case since this only happens when the argument types are:

1. float, long
2. double, long
3. long, float
4. long, double

I also found a bug in my PR. I had only updated calls for one of the `compare` methods. Caught that bug via the UT I added 😓

**Review by yupeng9 — APPROVED** [review]
Good catch!
