### PR TITLE
Fix the alias handling in single-stage engine

### LINKED ISSUE #11597: Aliasing a column with a function to the same name causes a StackOverflowException
A user discovered this running the equivalent of
```
select 
ActualElapsedTime,
coalesce(CancellationCode, 'test') as CancellationCode
from airlineStats
group by 1, 2
```

the `as CancellationCode` being the same as the column name causes `isAggregateExpression` to infinitely recurse.

### PR DESCRIPTION
**Pull request by Jackie-Jiang**
Fix 3 issues:
- Fix #11597 
- Alias should not be applied to filter (SQL standard)
- Fix the regression introduced by https://github.com/apache/pinot/pull/10815
## Incompatible

Alias can no longer be applied to filter to comply with standard SQL

### CODE REVIEW

File: pinot-common/src/main/java/org/apache/pinot/sql/parsers/rewriter/QueryRewriterFactory.java [hunk 1]
```diff
@@ -33,10 +33,14 @@ private QueryRewriterFactory() {
...
 
+  // NOTE:
+  //   OrdinalsUpdater must be applied after AliasApplier because OrdinalsUpdater can put the select expression
+  //   (reference) into the group-by list, but the alias should not be applied to the reference.
+  //   E.g. SELECT a + 1 AS a FROM table GROUP BY 1
   public static final List<String> DEFAULT_QUERY_REWRITERS_CLASS_NAMES =
       ImmutableList.of(CompileTimeFunctionsInvoker.class.getName(), SelectionsRewriter.class.getName(),
-          PredicateComparisonRewriter.class.getName(), OrdinalsUpdater.class.getName(),
-          AliasApplier.class.getName(), NonAggregationGroupByToDistinctQueryRewriter.class.getName());
+          PredicateComparisonRewriter.class.getName(), AliasApplier.class.getName(), OrdinalsUpdater.class.getName(),
```
Comment (xiangfu0) [inline pinot-common/src/main/java/org/apache/pinot/sql/parsers/rewriter/QueryRewriterFactory.java:42]: good catch!

File: pinot-common/src/main/java/org/apache/pinot/sql/parsers/rewriter/AliasApplier.java [hunk 2]
```diff
@@ -31,38 +29,30 @@
...
+      String alias = function.getOperands().get(1).getIdentifier().getName();
+      if (aliasMap.put(alias, function.getOperands().get(0)) != null) {
+        throw new SqlCompilationException("Find duplicate alias: " + alias);
       }
     }
     return aliasMap;
   }
 
-  private static void applyAlias(Map<Identifier, Expression> aliasMap, PinotQuery pinotQuery) {
-    Expression filterExpression = pinotQuery.getFilterExpression();
```
Comment (xiangfu0) [inline pinot-common/src/main/java/org/apache/pinot/sql/parsers/rewriter/AliasApplier.java:62]: My concern here is that this will silently return empty results once users upgrade.

Shall we instead throw exception if detected the alias in filter and explicitly mention that alias shouldn't be used, so users can at least find out the root cause and either roll back or fix queries before upgrade?

**Review by xiangfu0 — APPROVED** [review]
overall lgtm

**Comment by wirybeaver** [comment]
Just for curiosity, what regression do you observe when the https://github.com/apache/pinot/pull/10815 is introduced?

**Comment by xiangfu0** [comment]
> Just for curiosity, what regression do you observe when the #10815 is introduced?

master branch build failure:
https://github.com/apache/pinot/actions/runs/6230277100/job/16910046883
