### PR TITLE
Fixes SQL wildcard escaping in LIKE queries

### LINKED ISSUE #10849: LIKE doesn't seem to support escaping SQL wildcards
A query like:

`SELECT * FROM table WHERE col LIKE '%2\_2%'`

gets translated to 

`SELECT * FROM table WHERE REGEXP_LIKE(col, '2\\.2')`

Is this the right syntax for escaping SQL wildcards?

If so, this issue looks to be because [`likeToRegexpLike`](https://github.com/apache/pinot/blob/master/pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java#L35) doesn't handle escaped wildcards.

### PR DESCRIPTION
**Pull request by Aravind-Suresh**
Fixes #10849.

**Approach**: The escaping of SQL wildcards (`\_`, `\%`) is handled as a special case. The escaping of `\` is handled separately from the escaping of other meta characters.

**Test plan**: 
- Existing unit tests pass.
- Added unit tests to validate the specific case that this fix solves.
- Verified the behaviour by running an e2e query locally (```select * from starbucksStores where address like '%3\_9%' limit 10```): before the patch it returned zero records, but after the patch it matched the valid records only.

### CODE REVIEW

**Comment by atris** [comment]
@Aravind-Suresh Thanks for raising the PR. I will review this once the tests pass

**Review by tibrewalpratik17 — APPROVED** [review]

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 1]
```diff
@@ -18,16 +18,23 @@
...
 
-  /* Represents all metacharacters to be processed */
-  public static final String[] REGEXP_METACHARACTERS =
-      {"\\", "^", "$", ".", "{", "}", "[", "]", "(", ")", "*", "+", "?", "|", "<", ">", "-", "&", "/"};
+  /*
+   * Represents all metacharacters to be processed.
+   * This excludes the \ (back slash) character as that doubles up as an escape character as well.
+   * So it is handled separately in the conversion logic.
+   */
+  public static final Set<String> REGEXP_METACHARACTERS = ImmutableSet.of(
```
Comment (atris) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:36]: Why the move to a set? Since the number of characters is small, isn't an array more space efficient?

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 2]
```diff
@@ -64,24 +71,42 @@ public static String likeToRegexpLike(String likePattern) {
...
+    boolean isPrevCharBackSlash = false;
+    while (i < likePattern.length()) {
+      char c = likePattern.charAt(i);
       if (c == '_') {
-        sb.replace(i, i + 1, ".");
+        sb.append(isPrevCharBackSlash ? c : ".");
       } else if (c == '%') {
-        sb.replace(i, i + 1, ".*");
-        i++;
+        sb.append(isPrevCharBackSlash ? c : ".*");
```
Comment (atris) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:87]: Why was this logic moved out of escapeMetaCharacters?

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 3]
```diff
@@ -64,24 +71,42 @@ public static String likeToRegexpLike(String likePattern) {
...
+    // handling SQL wildcards by replacing them with corresponding regex equivalents
+    // we ignore them if the SQL wildcards are escaped
     int i = 0;
-    while (i < sb.length()) {
-      char c = sb.charAt(i);
+    boolean isPrevCharBackSlash = false;
+    while (i < likePattern.length()) {
+      char c = likePattern.charAt(i);
       if (c == '_') {
-        sb.replace(i, i + 1, ".");
```
Comment (atris) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:77]: NIT: Lets use constant named variables instead of symbols here

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 4]
```diff
@@ -64,24 +71,42 @@ public static String likeToRegexpLike(String likePattern) {
...
+        sb.append(isPrevCharBackSlash ? c : ".*");
+      } else if (REGEXP_METACHARACTERS.contains(String.valueOf(c))) {
+        sb.append('\\').append(c);
+      } else {
+        if (isPrevCharBackSlash) {
+          // this means the previous character is a \
+          // but it was not used for escaping SQL wildcards
+          // so let's escape this \ in the output
+          // this case is separately handled outside of the meta characters list
+          sb.append('\\');
```
Comment (atris) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:96]: Why can this be not merged with line 89?

**Review by atris — CHANGES_REQUESTED** [review]
In general, I think the code readability has been reduced by this PR and we should work on merging if branches, and retaining the abstraction of handling the processing in a separate method as was before

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 2 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:87]: So, escapeMetaCharacters was escaping every instance of a meta character. Now "\" was also a meta character, but we shouldn't escape that if that was used to escape the following character - like: \_, \%. Basically there are two flavours of "\" - one as a meta character, one as an escape character for the following character. We should escape the first and not the latter in the output. Since we can't replace every occurrence of "\" with "\\" - so I incorporated that logic here where if it's not before any SQL wildcard, we end up escaping it.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 4 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:96]: We can't merge this in line 89 as this requires look-ahead at the next character - we could do that as well, but instead of look-ahead, we look-back here. So if c = '\', we don't know if it should be escaped or not. We should escape it if the next character is not a SQL wildcard. So, this cannot be merged with line 89 where we escape every meta character (this is why '\' was removed from the meta characters list).

Let me know if I'm missing something here.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 1 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:36]: Ack, will fix this.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 3 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:77]: Ack, will fix this.

Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:77]: I've replaced the ones (BACK_SLASH) which occur more than once here. Rest I've left for readability.

File: pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java [hunk 5]
```diff
@@ -125,4 +125,27 @@ public void testTrailingSize2() {
     String regexpLikePattern = RegexpPatternConverterUtils.likeToRegexpLike("z%");
     assertEquals(regexpLikePattern, "^z");
   }
+
+  @Test
+  public void testEscapedWildcard1() {
+    String regexpLikePattern = RegexpPatternConverterUtils.likeToRegexpLike("a\\_b_\\");
```
Comment (chenboat) [inline pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java:131]: Is it correct that "b_" is translated "b."? Even it is correctly, it is not obvious. Can you add some comments why it is converted as such?

File: pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java [hunk 6]
```diff
@@ -125,4 +125,27 @@ public void testTrailingSize2() {
...
+    assertEquals(regexpLikePattern, "^a\\_b.\\\\$");
+    String luceneRegExpPattern = RegexpPatternConverterUtils.regexpLikeToLuceneRegExp(regexpLikePattern);
+    assertEquals(luceneRegExpPattern, "a\\_b.\\\\");
```
Comment (chenboat) [inline pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java:134]: Ditto as above.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 7]
```diff
@@ -64,27 +70,54 @@ public static String likeToRegexpLike(String likePattern) {
...
 
-    String escaped = escapeMetaCharacters(likePattern.substring(start, end));
-    StringBuilder sb = new StringBuilder(escaped.length() + 2);
+    likePattern = likePattern.substring(start, end);
+    StringBuilder sb = new StringBuilder();
     sb.append(prefix);
-    sb.append(escaped);
-    sb.append(suffix);
 
+    // handling SQL wildcards by replacing them with corresponding regex equivalents
```
Comment (chenboat) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:77]: Can you be more specific on what characters are wildchards in SQL? Please give a complete list.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 8]
```diff
@@ -64,27 +70,54 @@ public static String likeToRegexpLike(String likePattern) {
...
+    // handle trailing \
+    if (isPrevCharBackSlash) {
+      sb.append(BACK_SLASH);
     }
 
+    sb.append(suffix);
     return sb.toString();
   }
 
+  private static int indexOf(char[] arr, char c) {
```
Comment (chenboat) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:112]: why re-imple indexOf rather than using existing lib such as

https://commons.apache.org/proper/commons-collections/apidocs/org/apache/commons/collections4/IterableUtils.html#find-java.lang.Iterable-org.apache.commons.collections4.Predicate-

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 9]
```diff
@@ -64,27 +70,54 @@ public static String likeToRegexpLike(String likePattern) {
...
     sb.append(prefix);
-    sb.append(escaped);
-    sb.append(suffix);
 
+    // handling SQL wildcards by replacing them with corresponding regex equivalents
+    // we ignore them if the SQL wildcards are escaped
     int i = 0;
-    while (i < sb.length()) {
-      char c = sb.charAt(i);
+    boolean isPrevCharBackSlash = false;
```
Comment (chenboat) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:80]: Can we extract all codes below into a function about escape char handling? It is pretty long at the current form.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 7 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:77]: Ack, fixed it.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 8 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java]: Tried searching for it before -- didn't find one in an already included package.

But found Guava's Chars.indexOf which does this -- replaced it with that.

File: pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java (hunk 5 above)
Comment (Aravind-Suresh) [reply pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java:135]: Sure, added in-line comments to explain this.

File: pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java (hunk 6 above)
Comment (Aravind-Suresh) [reply pinot-common/src/test/java/org/apache/pinot/common/utils/RegexpPatternConverterUtilsTest.java:138]: Fixed it.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 9 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:96]: Done, fixed it.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 2 above)
Comment (atris) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:102]: That should not impact doing the processing in a separate method. I would still advise moving to a separate method to ensure a higher degree of readability.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 10]
```diff
@@ -64,24 +72,56 @@ public static String likeToRegexpLike(String likePattern) {
...
+  private static String escapeMetaCharsAndWildcards(String input, String prefix, String suffix) {
+    StringBuilder sb = new StringBuilder();
+    sb.append(prefix);
+    // handling SQL wildcards (_, %) by replacing them with corresponding regex equivalents
+    // we ignore them if the SQL wildcards are escaped
     int i = 0;
-    while (i < sb.length()) {
-      char c = sb.charAt(i);
+    boolean isPrevCharBackSlash = false;
+    while (i < input.length()) {
```
Comment (atris) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:97]: Nit: Cache this length locally

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 11]
```diff
@@ -64,24 +72,56 @@ public static String likeToRegexpLike(String likePattern) {
...
+          // but it was not used for escaping SQL wildcards
+          // so let's escape this \ in the output
+          // this case is separately handled outside of the meta characters list
+          sb.append(BACK_SLASH);
+        }
+        sb.append(c);
       }
-      i++;
+      isPrevCharBackSlash = (c == BACK_SLASH);
+      ++i;
```
Comment (atris) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:116]: Nit: Why the pre increment?

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java [hunk 12]
```diff
@@ -64,24 +72,56 @@ public static String likeToRegexpLike(String likePattern) {
...
+    while (i < input.length()) {
+      char c = input.charAt(i);
       if (c == '_') {
-        sb.replace(i, i + 1, ".");
+        sb.append(isPrevCharBackSlash ? c : ".");
       } else if (c == '%') {
-        sb.replace(i, i + 1, ".*");
-        i++;
+        sb.append(isPrevCharBackSlash ? c : ".*");
+      } else if (Chars.indexOf(REGEXP_METACHARACTERS, c) >= 0) {
```
Comment (atris) [inline pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:103]: Nit: I wonder if we can model this as a switch statement. The if branching hurts my eyes

**Review by atris — CHANGES_REQUESTED** [review]

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 11 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java:116]: Fixed it.

File: pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java (hunk 12 above)
Comment (Aravind-Suresh) [reply pinot-common/src/main/java/org/apache/pinot/common/utils/RegexpPatternConverterUtils.java]: Did a minor refactor to fix this.

**Review by atris — APPROVED** [review]
LGTM. Will merge post the run success
