### PR TITLE
Make ThreadResourceUsageProvider a Helper/Utility Class.

### LINKED ISSUE #16042: Change ThreadResourceUsageProvider to a utility or helper class
For every query execution thread, a ThreadResourceUsageProvider is created. Example for a worker:
```
    public static void setupWorker(int taskId, ThreadExecutionContext.TaskType taskType,
        @Nullable ThreadExecutionContext threadExecutionContext) {
      Tracing.getThreadAccountant().setThreadResourceUsageProvider(new ThreadResourceUsageProvider());
      Tracing.getThreadAccountant().setupWorker(taskId, taskType, threadExecutionContext);
    }
```
The ThreadResourceUsageAccountant  stores it in a thread local.
```
    // ThreadResourceUsageProvider(ThreadMXBean wrapper) per runner/worker thread
    private final ThreadLocal<ThreadResourceUsageProvider> _threadResourceUsageProvider;
```
However take a look at the code to get the memory allocation for a thread.
```
  public long getThreadAllocatedBytes() {
    try {
      return _isThreadMemoryMeasurementEnabled ? (long) SUN_THREAD_MXBEAN_GET_BYTES_ALLOCATED_METHOD
          .invoke(MX_BEAN, Thread.currentThread().getId()) - _startBytesAllocated : 0;
    } catch (IllegalAccessException | InvocationTargetException e) {
      LOGGER.error("Exception happened during the invocation of getting initial bytes allocated", e);
      return 0;
    }
  }
```
It is passing the id of the current thread: Thread.currentThread().getId() . So the function itself is not using any thread local information. 

There are a couple of non-static member variables in `ThreadResourceUsageProvider`. 

```
  // reference point for start time/bytes
  private final long _startTimeNs;
  private final long _startBytesAllocated;
```

These can be easily moved to `CPUMemThreadLevelAccountingObjects.ThreadEntry` class

 
Note that a large number of NPE was because `_threadResourceUsageProvider` was not set. So this change will fix a class of issues by getting rid of this per-thread object.

### PR DESCRIPTION
**Pull request by vrajat**
`ThreadResourceUsageProvider` has two functions:
* Provide utility functions to capture thread cpu and allocated bytes. 
* Snapshot start values for cpu and allocated bytes since the mxbean functions provide cumulative values.

The dual functionality complicated its usage in `PerQueryCpuMemAccountant`. A `ThreadResourceUsageProvider` object has to be stored in a thread local to remember the initial resource values. When a thread is assigned a task this thread local also has to be initialized. Else queries will fail with NPE. #15045 is an example.

This PR splits the functionality into
* `ThreadResourceUsageProvider` is now a pure utility class with only static functions
* `ThreadResourceSnapshot` maintains start values.

With these changes, the thread-local for `ThreadResourceUsageProvider` has been removed. The snapshot of resources is stored in the `ThreadEntry` thread-local itself. So a class of issues have been eliminated along with yet another thread-local. 

Closes #16042

### CODE REVIEW

File: pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceSnapshot.java [hunk 1]
```diff
@@ -0,0 +1,76 @@
...
+    _endAllocatedBytes = _startAllocatedBytes;
+  }
+
+  /**
+   * Gets the CPU time used so far in nanoseconds.
+   * Takes a current snapshot if not yet closed.
+   */
+  public long getCpuTimeNs() {
+    return _endCpuTime - _startCpuTime;
+  }
```
Comment (gortiz) [inline pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceSnapshot.java]: Javadoc is not correct, right? It isn't taking a snapshot. Also, what is the meaning of `closed` here?

File: pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceUsageProvider.java [hunk 2]
```diff
@@ -51,22 +51,28 @@ public class ThreadResourceUsageProvider {
...
-  private final long _startBytesAllocated;
+  @Deprecated
+  public long getThreadTimeNs() {
+    return 0;
+  }
+
+  @Deprecated
+  public long getThreadAllocatedBytes() {
+    return 0;
+  }
```
Comment (gortiz) [inline pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceUsageProvider.java:62]: Perhaps we should consider breaking backward compatibility with this change.

**Review by gortiz — APPROVED** [review]

**Comment by gortiz** [comment]
I have approved the PR, but I would like to address some comments before merging. Also tests are failing.

File: pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceSnapshot.java (hunk 1 above)
Comment (vrajat) [reply pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceSnapshot.java]: I've fixed the javadoc and the code. This was left over from an initial version.

File: pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceUsageProvider.java (hunk 2 above)
Comment (vrajat) [reply pinot-spi/src/main/java/org/apache/pinot/spi/accounting/ThreadResourceUsageProvider.java:62]: I had a similar conversation with @vvivekiyer as well. I had suggested a separate PR to remove all the unnecessary code in a single PR. There will be a few more code blocks deprecated as well.

**Comment by vrajat** [comment]
Test failures seem unrelated to the diff.

```
RefreshSegmentMinionClusterIntegrationTest.checkColumnAddition:386 expected [717.6666666666666] but found [164.66666666666666]
[INFO] 
```
 in ` Pinot Integration Test Set 2` passes when run locally. I think its flaky.

I am seeing the same failures in `Pinot Unit Test Set 1` in master as well.

**Comment by vrajat** [comment]
All tests have passed
